/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Provider.PolynomialHomogenization.Root.Corrector.C1BaseSlopeEnergyControl
import HCPoly.Provider.PolynomialHomogenization.Root.Corrector.C1CanonicalProjectionAbsoluteDecay

/-!
# The simultaneous-slope row, with its slope norm exported

One datum the simultaneous-slope row discards is needed here: a bound on
the Euclidean norm of the slope it returns.  The bound is **already derived**
inside `Root.exists_scalarIdentityInfiniteCorrectorC1Constants` — the block

```
euclideanNorm e ≤ 2 * euclideanNorm (P e) = 2 * euclideanNorm bBase
              ≤ 2 * K * h1EnergyNormOnCube (originCube d m) a u.toH1
```

from `exists_canonicalFiniteCorrectorProjectionInverseControlThreshold` and
`exists_baseExactMinimizerSlopeEnergyConstants` — and is used there only to
absorb `euclideanNorm e` into the reverse comparison.  This module exports it.

Why it is needed: the large-scale C¹ slope approximation's ball terminal must
hold at **every** radius
`r ∈ Icc rStart R`, including the near-terminal band `r > R / (108 √d)` where
the canonical outer cube of `r` overshoots every triadic cube contained in the
ball of radius `R`.  There the cube row says nothing, and the only route is to
bound the corrector's own energy, `‖e + ∇Φ_e‖ ≤ B ‖e‖`
(`exists_scalarIdentityGoodTailJointWeightedGradientBoundConstant`), and then
`‖e‖` by the solution's energy — which is exactly this export.

The statement below is the infinite-corrector C¹ constants statement
with two additions: a second constant `Cslope`, and the conjunct
`euclideanNorm e ≤ Cslope * h1EnergyNormOnCube (originCube d m) a u.toH1`.
The proof is the one **byte for byte**, with the already-present slope
block moved ahead of the `refine` that returns `e`; it is generated by an
assert-guarded exact-match script, never retyped.
-/

namespace Homogenization
namespace HighContrast
namespace Root

open MeasureTheory
open scoped ENNReal

noncomputable section

/-- A scalar-identity cube solution admits one infinite-corrector slope which
works simultaneously on every intermediate centered cube. -/
theorem exists_scalarIdentityInfiniteCorrectorC1ConstantsWithSlope
    (d : ℕ) [NeZero d] (s eta : ℝ)
    (hs : 0 < s) (hs_lt : s < 1 / 2)
    (hetaHalf : 1 / 2 ≤ eta) (heta1 : eta < 1) :
    ∃ C Cslope c : ℝ, 0 < C ∧ 0 < Cslope ∧ c ∈ Set.Ioo (0 : ℝ) 1 ∧
      ∀ (a : Book.Ch02.TriadicCoeffFamily d) (delta : ℝ) (n0 : ℤ),
        delta ∈ Set.Ioc (0 : ℝ) c →
        ScalarIdentityGoodTail a s delta n0 →
        ∀ (_hCauchy : FiniteAffineCorrectionLocalCauchy a)
          (Phi : Vec d → NormalizedLocalH1Carrier d),
          IsFiniteAffineCorrectionJointLocalEquation a Phi →
          ∀ (n m : ℕ), n0 ≤ (n : ℤ) → n + 2 ≤ m →
            ∀ u : Book.Ch03.CubeSolution (originCube d (m : ℤ)) a,
              ∃ e : Vec d,
                euclideanNorm e ≤ Cslope *
                  Book.Ch03.h1EnergyNormOnCube
                    (originCube d (m : ℤ)) a u.toH1 ∧
                ∀ q : ℕ, q ∈ Finset.Icc n m →
                weightedGradNorm
                    (a.coeffOn (originCube d (q : ℤ))).toCoeffField
                    (openCubeSet (originCube d (q : ℤ)))
                    (fun x ↦ u.toH1.grad x -
                      (e + (Phi e).globalGradientRepresentative x)) ≤
                  ENNReal.ofReal
                      (C * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ))) *
                    weightedGradNorm
                      (a.coeffOn (originCube d (m : ℤ))).toCoeffField
                      (openCubeSet (originCube d (m : ℤ))) u.toH1.grad := by
  obtain ⟨Cfix, cFix, hCfix, hcFix, hfixed⟩ :=
    exists_scalarIdentityFiniteAffineFixedBaseDecayConstants
      d s eta hs hs_lt hetaHalf heta1
  obtain ⟨Cabs, cAbs, hCabs, hcAbs, habs⟩ :=
    exists_canonicalFiniteCorrectorAbsoluteDecayConstants
      d s eta hs hs_lt hetaHalf heta1
  obtain ⟨cInv, hcInv, hinverse⟩ :=
    exists_canonicalFiniteCorrectorProjectionInverseControlThreshold
      d s hs hs_lt
  obtain ⟨K, cBase, hK, hcBase, hbase⟩ :=
    exists_baseExactMinimizerSlopeEnergyConstants d s hs hs_lt
  let C : ℝ := Cfix + 2 * K * Cabs
  let c : ℝ := min cFix (min cAbs (min cInv cBase))
  have hC : 0 < C := add_pos hCfix (mul_pos (mul_pos (by norm_num) hK) hCabs)
  have hc0 : 0 < c := by
    dsimp only [c]
    exact lt_min hcFix.1 (lt_min hcAbs.1 (lt_min hcInv.1 hcBase.1))
  have hc1 : c < 1 := (min_le_left cFix _).trans_lt hcFix.2
  refine ⟨C, 2 * K, c, hC, mul_pos (by norm_num) hK, ⟨hc0, hc1⟩, ?_⟩
  intro a delta n0 hdelta hgood _hCauchy Phi hPhi n m hn hnm2 u
  let hCauchy := _hCauchy
  have hdeltaFix : delta ∈ Set.Ioc (0 : ℝ) cFix :=
    ⟨hdelta.1, hdelta.2.trans (min_le_left _ _)⟩
  have hdeltaAbs : delta ∈ Set.Ioc (0 : ℝ) cAbs :=
    ⟨hdelta.1, hdelta.2.trans
      ((min_le_right _ _).trans (min_le_left _ _))⟩
  have hdeltaInv : delta ∈ Set.Ioc (0 : ℝ) cInv :=
    ⟨hdelta.1, hdelta.2.trans
      ((min_le_right _ _).trans
        ((min_le_right _ _).trans (min_le_left _ _)))⟩
  have hdeltaBase : delta ∈ Set.Ioc (0 : ℝ) cBase :=
    ⟨hdelta.1, hdelta.2.trans
      ((min_le_right _ _).trans
        ((min_le_right _ _).trans (min_le_right _ _)))⟩
  obtain ⟨hT, hbij, hinv⟩ :=
    hinverse a delta n0 hdeltaInv hgood hCauchy Phi hPhi n m hn hnm2
  let P := finiteCorrectorWeightedProjection a hCauchy
    (by omega : n ≤ m) hT
  let hnm : (n : ℤ) ≤ (m : ℤ) := by exact_mod_cast (show n ≤ m by omega)
  let bBase := finiteAffineExactMinimizer a hnm u
  obtain ⟨e, he⟩ := hbij.2 bBase
  have hb := hbase a delta n m hdeltaBase
    (hgood.mono_start hn) hnm2 u
  have heNorm : euclideanNorm e ≤
      2 * K * Book.Ch03.h1EnergyNormOnCube
        (originCube d (m : ℤ)) a u.toH1 := by
    calc
      euclideanNorm e ≤ 2 * euclideanNorm (P e) := hinv e
      _ = 2 * euclideanNorm bBase := by rw [he]
      _ ≤ 2 * (K * Book.Ch03.h1EnergyNormOnCube
          (originCube d (m : ℤ)) a u.toH1) := by gcongr
      _ = 2 * K * Book.Ch03.h1EnergyNormOnCube
          (originCube d (m : ℤ)) a u.toH1 := by ring
  refine ⟨e, heNorm, ?_⟩
  intro q hq
  have hnq : n ≤ q := (Finset.mem_Icc.mp hq).1
  have hqm : q ≤ m := (Finset.mem_Icc.mp hq).2
  let hqmZ : (q : ℤ) ≤ (m : ℤ) := by exact_mod_cast hqm
  let uQ := (finiteCubeSolutionRestriction a hqmZ u).toH1
  let finiteQ := (finiteCubeSolutionRestriction a hqmZ
    (finiteAffineCubeSolution a (m : ℤ) (P e))).toH1
  let jointQ := finiteAffineCorrectionJointLocalH1 a hCauchy e q
  have htri := weightedGradNorm_sub_le_add_sub_h1 a (q : ℤ)
    uQ finiteQ jointQ
  have hfixedRaw := hfixed a delta n m hdeltaFix
    (hgood.mono_start hn) hnm2 u q hq
  have hfixedQ : weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ uQ.grad x - finiteQ.grad x) ≤
      ENNReal.ofReal
          (Cfix * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ))) *
        finiteAffineGradientExcess a (m : ℤ) (m : ℤ) u := by
    have heBase : P e = bBase := he
    simpa only [uQ, finiteQ, finiteCubeSolutionRestriction_grad,
      heBase, bBase, hnm, P] using hfixedRaw
  have hexcessOuter : finiteAffineGradientExcess a (m : ℤ) (m : ℤ) u ≤
      weightedGradNorm
        (a.coeffOn (originCube d (m : ℤ))).toCoeffField
        (openCubeSet (originCube d (m : ℤ))) u.toH1.grad := by
    have hcandidate := finiteAffineGradientExcess_le
      a (m : ℤ) (m : ℤ) u (0 : Vec d)
    have hzero := finiteAffineSolution_grad_smul
      a (m : ℤ) (0 : ℝ) (0 : Vec d)
    have hzero' : (finiteAffineSolution a (m : ℤ) (0 : Vec d)).toH1.grad
        =ᵐ[volumeMeasureOn (openCubeSet (originCube d (m : ℤ)))]
          fun _ ↦ 0 := by
      simpa only [zero_smul] using hzero
    refine hcandidate.trans_eq ?_
    apply weightedGradNorm_congr_ae
    filter_upwards [hzero'] with x hx
    rw [hx]
    simp
  have hfixedEnergy : weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ uQ.grad x - finiteQ.grad x) ≤
      ENNReal.ofReal
          (Cfix * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ))) *
        weightedGradNorm
          (a.coeffOn (originCube d (m : ℤ))).toCoeffField
          (openCubeSet (originCube d (m : ℤ))) u.toH1.grad :=
    hfixedQ.trans (mul_le_mul_of_nonneg_left hexcessOuter bot_le)
  have habsRaw := habs a delta n0 hdeltaAbs hgood hCauchy Phi hPhi
    n m hn hnm2 hT e q hq
  have hPhiLimit : IsFiniteAffineCorrectionJointLocalLimit a Phi := by
    simpa only [IsFiniteAffineCorrectionJointLocalLimit] using hPhi.1
  have hPhiEq : Phi = finiteAffineCorrectionJointLocalLimit a hCauchy :=
    (isFiniteAffineCorrectionJointLocalLimit_iff_eq a hCauchy Phi).mp hPhiLimit
  have hboundary :
      (show H1Function (localGradientCube d q) from by
        simpa only [localGradientCube, Book.Ch02.cubeDomain_coe] using
          finiteAffineBoundaryH1 (q : ℤ) e).grad = fun _ ↦ e := by
    simpa only using finiteAffineBoundaryH1_grad (m := (q : ℤ)) e
  have hglobal :=
    (finiteAffineCorrectionJointLocalLimit a hCauchy e).globalGradientRepresentative_ae_eq_localH1Gradient q
  have hjointField : jointQ.grad =ᵐ[volumeMeasureOn
      (openCubeSet (originCube d (q : ℤ)))]
      (fun x ↦ e + (Phi e).globalGradientRepresentative x) := by
    rw [hPhiEq]
    filter_upwards [hglobal] with x hx
    simp only [jointQ, finiteAffineCorrectionJointLocalH1,
      H1Function.add_grad, hboundary, hx]
  have hfiniteField : finiteQ.grad =
      (finiteAffineSolution a (m : ℤ) (P e)).toH1.grad := by
    rfl
  have habsQ : weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ jointQ.grad x - finiteQ.grad x) ≤
      ENNReal.ofReal
        (Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)) *
          euclideanNorm e) := by
    refine (weightedGradNorm_congr_ae _ _ ?_).trans_le habsRaw
    filter_upwards [hjointField] with x hx
    rw [hx, hfiniteField]
  have hreverseQ : weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ finiteQ.grad x - jointQ.grad x) ≤
      ENNReal.ofReal
        (Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)) *
          euclideanNorm e) := by
    rw [weightedGradNorm_sub_comm_h1 a (q : ℤ) finiteQ jointQ]
    exact habsQ
  have hreverseEnergy : weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ finiteQ.grad x - jointQ.grad x) ≤
      ENNReal.ofReal
          (2 * K * Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ))) *
        weightedGradNorm
          (a.coeffOn (originCube d (m : ℤ))).toCoeffField
          (openCubeSet (originCube d (m : ℤ))) u.toH1.grad := by
    rw [weightedGradNorm_eq_ofReal_h1EnergyNormOnCube]
    refine hreverseQ.trans ?_
    rw [← ENNReal.ofReal_mul
      (p := 2 * K * Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)))
      (q := Book.Ch03.h1EnergyNormOnCube
        (originCube d (m : ℤ)) a u.toH1)
      (mul_nonneg
        (mul_nonneg (mul_nonneg (by norm_num) hK.le) hCabs.le)
        (Real.rpow_nonneg (by norm_num) _))]
    exact ENNReal.ofReal_le_ofReal (by
      have hrate := Real.rpow_nonneg (by norm_num : (0 : ℝ) ≤ 3)
        (-eta * ((m - q : ℕ) : ℝ))
      calc
        Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)) * euclideanNorm e ≤
            Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)) *
              (2 * K * Book.Ch03.h1EnergyNormOnCube
                (originCube d (m : ℤ)) a u.toH1) := by gcongr
        _ = (2 * K * Cabs * Real.rpow 3
              (-eta * ((m - q : ℕ) : ℝ))) *
            Book.Ch03.h1EnergyNormOnCube
              (originCube d (m : ℤ)) a u.toH1 := by ring)
  have htargetEq : weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ uQ.grad x - jointQ.grad x) =
      weightedGradNorm
        (a.coeffOn (originCube d (q : ℤ))).toCoeffField
        (openCubeSet (originCube d (q : ℤ)))
        (fun x ↦ u.toH1.grad x -
          (e + (Phi e).globalGradientRepresentative x)) := by
    apply weightedGradNorm_congr_ae
    filter_upwards [hjointField] with x hx
    rw [hx]
    rfl
  rw [← htargetEq]
  calc
    _ ≤ weightedGradNorm
          (a.coeffOn (originCube d (q : ℤ))).toCoeffField
          (openCubeSet (originCube d (q : ℤ)))
          (fun x ↦ uQ.grad x - finiteQ.grad x) +
        weightedGradNorm
          (a.coeffOn (originCube d (q : ℤ))).toCoeffField
          (openCubeSet (originCube d (q : ℤ)))
          (fun x ↦ finiteQ.grad x - jointQ.grad x) := htri
    _ ≤ (ENNReal.ofReal
          (Cfix * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ))) +
        ENNReal.ofReal
          (2 * K * Cabs * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)))) *
        weightedGradNorm
          (a.coeffOn (originCube d (m : ℤ))).toCoeffField
          (openCubeSet (originCube d (m : ℤ))) u.toH1.grad := by
      rw [add_mul]
      exact add_le_add hfixedEnergy hreverseEnergy
    _ = ENNReal.ofReal
          (C * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ))) *
        weightedGradNorm
          (a.coeffOn (originCube d (m : ℤ))).toCoeffField
          (openCubeSet (originCube d (m : ℤ))) u.toH1.grad := by
      congr 1
      rw [← ENNReal.ofReal_add
        (p := Cfix * Real.rpow 3 (-eta * ((m - q : ℕ) : ℝ)))
        (q := 2 * K * Cabs * Real.rpow 3
          (-eta * ((m - q : ℕ) : ℝ)))
        (mul_nonneg hCfix.le (Real.rpow_nonneg (by norm_num) _))
        (mul_nonneg
          (mul_nonneg (mul_nonneg (by norm_num) hK.le) hCabs.le)
          (Real.rpow_nonneg (by norm_num) _))]
      congr 1
      dsimp only [C]
      ring

end

end Root
end HighContrast
end Homogenization
