/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Setup.Response
import Homogenization.Book.Ch04.SourceMu
import Homogenization.CoarseGraining.OriginCubeOpenBridge

/-!
# Measurability of the coarse response over the coefficient space

Every entry of the variational coarse block `𝐀(□_m; ·)` of `s.introduction` is
measurable for the canonical measurable structure of the coefficient space,
which is the global sigma-field `F = F(ℝ^d)` generated by the smooth linear
statistics.  Measurability is therefore a fact about the coefficient space
alone: it holds for every law at once, and the well-formedness predicate
`HasMeasurableCoarseBlock` that `e.Theta.m` presupposes never has to be
assumed.

The entries reduce to the variational quantity `Mu` at the four doubled vectors
built from a pair of basis directions, so the whole statement is the
measurability of `a ↦ Mu (□_m) Q a`.  That is obtained by transporting the
coarse-grained energy along a representative map into CoarseGraining's exact
coarse-source carrier, whose own local sigma-fields are generated by exactly the
same bilinear test integrals: the representative map pulls the generators back to
the generators, and `Mu` only sees the almost everywhere class of the field, so
the value is unchanged.
-/

namespace Homogenization
namespace HighContrast

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-! ## A representative in the exact coarse-source carrier -/

/-- The Euclidean ball lies in the ambient sup-norm ball of the same radius:
every coordinate of a vector is bounded by its Euclidean norm. -/
private theorem mem_metricBall_of_mem_euclideanBall {R : ℝ} (hR : 0 < R)
    {x : Vec d} (hx : x ∈ Source.Coarse.euclideanBall (d := d) R) :
    x ∈ Metric.ball (0 : Vec d) R := by
  have hxR : euclideanNorm x < R := hx
  have hsq : vecNormSq x < R ^ 2 := by
    have h := pow_lt_pow_left₀ hxR (euclideanNorm_nonneg x) two_ne_zero
    rwa [euclideanNorm_sq] at h
  refine mem_ball_zero_iff.2 ((pi_norm_lt_iff hR).2 fun i => ?_)
  have h1 : x i ^ 2 ≤ vecNormSq x := sq_apply_le_vecNormSq x i
  rw [Real.norm_eq_abs]
  refine lt_of_pow_lt_pow_left₀ 2 hR.le ?_
  rw [sq_abs]
  linarith only [h1, hsq]

/-- Every point of the coefficient space is represented, up to a null set, by a
field of the exact coarse-source carrier: a measurable field that is uniformly
elliptic on every ball with reciprocal constants.  The sample's ellipticity
constants on that ball supply the reciprocal constant, once normalized to lie in
`(0, 1]`. -/
private theorem exists_sourceCarrier_ae_eq (a : CoeffSpace d) :
    ∃ b : Source.Coarse.Carrier d,
      (⇑a.1 : Vec d → Mat d) =ᵐ[volume] (b.1 : CoeffField d) := by
  obtain ⟨f, hmeas, hae, hloc⟩ :=
    exists_locally_pointwise_elliptic_representative a.2
  refine ⟨⟨f, ?_, ?_⟩, hae⟩
  · intro i j
    exact (measurable_pi_apply j).comp ((measurable_pi_apply i).comp hmeas)
  · intro R hR1
    have hR : (0 : ℝ) < R := lt_of_lt_of_le one_pos hR1
    obtain ⟨lam, Lam, hlam, hle, hell⟩ := hloc R hR
    have hLam : 0 < Lam := lt_of_lt_of_le hlam hle
    refine ⟨min (min lam Lam⁻¹) 1, ?_, min_le_right _ _, ?_⟩
    · exact lt_min (lt_min hlam (by positivity)) one_pos
    · intro x hx
      have hpos : (0 : ℝ) < min (min lam Lam⁻¹) 1 :=
        lt_min (lt_min hlam (by positivity)) one_pos
      have hle_lam : min (min lam Lam⁻¹) 1 ≤ lam :=
        le_trans (min_le_left _ _) (min_le_left _ _)
      have hle_inv : min (min lam Lam⁻¹) 1 ≤ Lam⁻¹ :=
        le_trans (min_le_left _ _) (min_le_right _ _)
      have hLam_le : Lam ≤ (min (min lam Lam⁻¹) 1)⁻¹ := by
        have h := inv_le_inv₀ (a := Lam⁻¹) (b := min (min lam Lam⁻¹) 1)
          (by positivity) hpos
        rw [inv_inv] at h
        exact h.2 hle_inv
      exact (hell x (mem_metricBall_of_mem_euclideanBall hR hx)).mono hpos hle_lam
        hLam_le

/-- The chosen coarse-source representative of a point of the coefficient
space. -/
def sourceRepresentative (a : CoeffSpace d) : Source.Coarse.Carrier d :=
  (exists_sourceCarrier_ae_eq a).choose

/-- The coarse-source representative carries the sample's field. -/
theorem sourceRepresentative_ae_eq (a : CoeffSpace d) :
    (⇑a.1 : Vec d → Mat d) =ᵐ[volume] ((sourceRepresentative a).1 : CoeffField d) :=
  (exists_sourceCarrier_ae_eq a).choose_spec

/-- The bilinear test integrals of the coarse-source carrier pull back along the
representative map to the generating linear statistics of `F(U)`: both are the
same integral, and the two integrands agree almost everywhere. -/
theorem bilinearTest_sourceRepresentative (e e' : Vec d) (φ : Vec d → ℝ)
    (a : CoeffSpace d) :
    Source.Coarse.bilinearTest e e' φ (sourceRepresentative a) =
      coeffPairing e e' φ a := by
  unfold Source.Coarse.bilinearTest coeffPairing
  refine integral_congr_ae ?_
  filter_upwards [sourceRepresentative_ae_eq a] with x hx
  rw [hx]

/-- **The representative map is measurable** for the global sigma-fields: it
pulls each generator of the coarse-source carrier back to a generator of
`F(ℝ^d)`, the test functions of the two families being the same. -/
theorem measurable_sourceRepresentative :
    Measurable (sourceRepresentative (d := d)) := by
  change @Measurable (CoeffSpace d) (Source.Coarse.Carrier d)
    (coeffSigma d Set.univ)
    (MeasurableSpace.generateFrom
      {s | ∃ (e e' : Vec d) (φ : Vec d → ℝ),
        Source.Coarse.SmoothCompactProbe φ ∧ tsupport φ ⊆ (Set.univ : Set (Vec d)) ∧
        ∃ t : Set ℝ, MeasurableSet t ∧ s = Source.Coarse.bilinearTest e e' φ ⁻¹' t})
    sourceRepresentative
  apply measurable_generateFrom
  rintro s ⟨e, e', φ, hφ, -, t, ht, rfl⟩
  have hset : sourceRepresentative (d := d) ⁻¹'
      (Source.Coarse.bilinearTest e e' φ ⁻¹' t) = coeffPairing e e' φ ⁻¹' t := by
    ext a
    change Source.Coarse.bilinearTest e e' φ (sourceRepresentative a) ∈ t ↔ _
    rw [bilinearTest_sourceRepresentative]
    rfl
  rw [hset]
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨e, e', φ, ⟨hφ.smooth, hφ.compact, Set.subset_univ _⟩, t, ht, rfl⟩

/-! ## The variational quantity is measurable -/

/-- In dimension zero both realizations of a triadic cube are the whole space. -/
private theorem centeredCube_eq_cubeSet_of_dim_zero (hd : d = 0) (m : ℤ) :
    centeredCube d m = cubeSet (originCube d m) := by
  subst hd
  ext x
  exact ⟨fun _ i => i.elim0, fun _ i => i.elim0⟩

/-- The variational quantity does not distinguish the open realization `□_m` of
the centered triadic cube from the half-open realization used internally. -/
theorem Mu_centeredCube_eq_Mu_cubeSet (m : ℤ) (Q : BlockVec d) (f : CoeffField d) :
    Mu (centeredCube d m) Q f = Mu (cubeSet (originCube d m)) Q f := by
  rcases Nat.eq_zero_or_pos d with hd | hd
  · rw [centeredCube_eq_cubeSet_of_dim_zero hd]
  · haveI : NeZero d := ⟨by omega⟩
    exact (Mu_cubeSet_originCube_eq_openCubeSet m Q f).symm

/-- **The coarse-grained energy of a centered cube is measurable** on the
coefficient space, for the global sigma-field `F(ℝ^d)`.  The coarse-source
energy is local for the bilinear test sigma-field of the cube, hence measurable
for the global one, and the representative map is measurable and leaves the
energy unchanged. -/
theorem measurable_Mu_centeredCube (m : ℤ) (Q : BlockVec d) :
    Measurable fun a : CoeffSpace d => Mu (centeredCube d m) Q (⇑a.1 : CoeffField d) := by
  have hloc : @Measurable (Source.Coarse.Carrier d) ℝ
      (Source.Coarse.localSigma (cubeSet (originCube d m))
        (measurableSet_cubeSet (originCube d m))) _
      (fun b : Source.Coarse.Carrier d =>
        Mu (cubeSet (originCube d m)) Q (b.1 : CoeffField d)) :=
    Book.Ch04.isSourceLocalRandomVariable_Mu_cubeSet (originCube d m) Q
  have hglob : Measurable
      fun b : Source.Coarse.Carrier d => Mu (cubeSet (originCube d m)) Q (b.1 : CoeffField d) :=
    Measurable.mono hloc
      (Source.Coarse.localSigma_mono (measurableSet_cubeSet _) MeasurableSet.univ
        (Set.subset_univ _)) le_rfl
  have hEq : (fun a : CoeffSpace d => Mu (centeredCube d m) Q (⇑a.1 : CoeffField d)) =
      (fun b : Source.Coarse.Carrier d =>
        Mu (cubeSet (originCube d m)) Q (b.1 : CoeffField d)) ∘ sourceRepresentative := by
    funext a
    rw [Function.comp_apply, Mu_centeredCube_eq_Mu_cubeSet,
      Mu_congr_of_ae_eq (ae_restrict_of_ae (sourceRepresentative_ae_eq a)) Q]
  rw [hEq]
  exact hglob.comp measurable_sourceRepresentative

/-! ## The coarse response is measurable -/

/-- **Every entry of the coarse block response on a centered cube is
measurable** for the canonical measurable structure of the coefficient space:
the entries are the variational quantities at the four doubled vectors built
from a pair of basis directions. -/
theorem measurable_blockMatEntry_coarseBlock (m : ℤ) (α β : BlockCoord d) :
    Measurable fun a : CoeffSpace d =>
      blockMatEntry (coarseBlock (centeredCube d m) a) α β := by
  simp only [coarseBlock, blockMatEntry_coarseBlockMatrix]
  by_cases h : α = β
  · simp only [if_pos h]
    exact (measurable_Mu_centeredCube m (blockBasis α)).const_mul 2
  · simp only [if_neg h]
    exact ((measurable_Mu_centeredCube m (blockBasis α + blockBasis β)).sub
      (measurable_Mu_centeredCube m (blockBasis α))).sub
      (measurable_Mu_centeredCube m (blockBasis β))

/-- **The coarse response is measurable over every law**: the well-formedness
predicate that `e.Theta.m` presupposes is a theorem of the coefficient space,
not an assumption on the law. -/
theorem hasMeasurableCoarseBlock_centeredCube (P : Measure (CoeffSpace d)) (m : ℤ) :
    HasMeasurableCoarseBlock P (centeredCube d m) :=
  fun α β => (measurable_blockMatEntry_coarseBlock m α β).aestronglyMeasurable

end

end HighContrast
end Homogenization
