/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Setup
import Mathlib.Analysis.Calculus.BumpFunction.Convolution

/-!
# The local sigma-fields separate points

The sigma-field `F(U)` of the coefficient space of `s.introduction` is
generated by the smooth linear statistics with test support inside `U`; the
global sigma-field `F` is generated by all of them.  That is an uncountable
generating family, so it is
not immediate that `F` distinguishes two coefficient fields; and without that,
no law on the coefficient space can be pinned to a prescribed field, and the
almost sure hypotheses of `e.coarse.ellipticity` cannot be tested on a
concrete law.

This file supplies the countable determining family: the statistics against the
translates of a fixed sequence of normalized smooth bumps, centred at the points
of a countable dense set.  Continuity of the mollification identifies it on all
of space from its values on the dense set, and the almost everywhere convergence
of mollifications at Lebesgue points recovers the field.  Consequently every
singleton of the coefficient space is measurable for `F`.
-/

namespace Homogenization
namespace HighContrast

open MeasureTheory Filter ContinuousLinearMap
open scoped Convolution

noncomputable section

variable {d : ℕ}

/-! ## A countable family of mollifiers -/

/-- The mollifier scale sequence: inner radius `1/(n+1)`, outer radius
`2/(n+1)`. -/
def witnessBump (d : ℕ) (n : ℕ) : ContDiffBump (0 : Vec d) where
  rIn := 1 / (n + 1)
  rOut := 2 / (n + 1)
  rIn_pos := by positivity
  rIn_lt_rOut := by
    have h : (0 : ℝ) < (n : ℝ) + 1 := by positivity
    rw [div_lt_div_iff_of_pos_right h]
    norm_num

/-- The normalized mollifier of scale index `n`. -/
def witnessMollifier (d : ℕ) (n : ℕ) : Vec d → ℝ :=
  (witnessBump d n).normed volume

/-- The test function pairing a field against the mollifier centred at `q`. -/
def mollifierTest (d : ℕ) (n : ℕ) (q : Vec d) : Vec d → ℝ :=
  fun y => witnessMollifier d n (q - y)

theorem contDiff_witnessMollifier (n : ℕ) :
    ContDiff ℝ (⊤ : ℕ∞) (witnessMollifier d n) :=
  (witnessBump d n).contDiff_normed

theorem hasCompactSupport_witnessMollifier (n : ℕ) :
    HasCompactSupport (witnessMollifier d n) :=
  (witnessBump d n).hasCompactSupport_normed

/-- Each mollifier test function is an admissible generator of the global
sigma-field. -/
theorem isLocalTest_mollifierTest (n : ℕ) (q : Vec d) :
    IsLocalTest (Set.univ : Set (Vec d)) (mollifierTest d n q) := by
  have hsub : ContDiff ℝ (⊤ : ℕ∞) (fun y : Vec d => q - y) :=
    contDiff_const.sub contDiff_id
  refine ⟨by
      simpa [mollifierTest, Function.comp_def] using
        (contDiff_witnessMollifier (d := d) n).comp hsub, ?_, Set.subset_univ _⟩
  simpa [mollifierTest, Function.comp_def] using
    (hasCompactSupport_witnessMollifier (d := d) n).comp_homeomorph (Homeomorph.subLeft q)

theorem tendsto_witnessBump_rOut :
    Tendsto (fun n : ℕ => (witnessBump d n).rOut) atTop (nhds 0) := by
  have h : Tendsto (fun n : ℕ => (2 : ℝ) * (1 / ((n : ℝ) + 1))) atTop (nhds (2 * 0)) :=
    tendsto_one_div_add_atTop_nhds_zero_nat.const_mul 2
  rw [mul_zero] at h
  refine h.congr fun n => ?_
  show (2 : ℝ) * (1 / ((n : ℝ) + 1)) = 2 / ((n : ℝ) + 1)
  ring

theorem witnessBump_rOut_le (n : ℕ) :
    (witnessBump d n).rOut ≤ 2 * (witnessBump d n).rIn := by
  show (2 : ℝ) / ((n : ℝ) + 1) ≤ 2 * (1 / ((n : ℝ) + 1))
  rw [mul_one_div]

/-- **The countable determining family.**  A locally integrable function whose
mollifier statistics vanish at every point of a dense set, at every scale of the
sequence, vanishes almost everywhere. -/
theorem ae_eq_zero_of_mollifierTest_eq_zero (f : Vec d → ℝ)
    (hf : LocallyIntegrable f volume) (Q : Set (Vec d)) (hQ : Dense Q)
    (h : ∀ n : ℕ, ∀ q ∈ Q, ∫ y, mollifierTest d n q y * f y ∂volume = 0) :
    ∀ᵐ x ∂volume, f x = 0 := by
  have hconv : ∀ n : ℕ, (witnessMollifier d n ⋆[lsmul ℝ ℝ, volume] f) = 0 := by
    intro n
    have hcont : Continuous (witnessMollifier d n ⋆[lsmul ℝ ℝ, volume] f) :=
      (hasCompactSupport_witnessMollifier n).continuous_convolution_left _
        (contDiff_witnessMollifier n).continuous hf
    refine hcont.ext_on hQ continuous_const ?_
    intro q hq
    show (witnessMollifier d n ⋆[lsmul ℝ ℝ, volume] f) q = 0
    rw [convolution_lsmul_swap]
    simpa [mollifierTest] using h n q hq
  have hae := ContDiffBump.ae_convolution_tendsto_right_of_locallyIntegrable
      (μ := (volume : Measure (Vec d))) (φ := witnessBump d) (l := atTop) (K := 2) (g := f)
      tendsto_witnessBump_rOut (Filter.Eventually.of_forall witnessBump_rOut_le) hf
  filter_upwards [hae] with x hx
  have hzero : Tendsto
      (fun n : ℕ => ((witnessBump d n).normed volume ⋆[lsmul ℝ ℝ, volume] f) x)
      atTop (nhds 0) := by
    refine tendsto_const_nhds.congr fun n => ?_
    have hn := congrFun (hconv n) x
    simpa [witnessMollifier] using hn.symm
  exact tendsto_nhds_unique hx hzero

/-! ## Entries of a coefficient field -/

theorem coeffPairing_basis (i j : Fin d) (φ : Vec d → ℝ) (a : CoeffSpace d) :
    coeffPairing (Pi.single i 1) (Pi.single j 1) φ a =
      ∫ x, (a.1 x) j i * φ x ∂volume := by
  simp only [coeffPairing, matVecMul_single, vecDot_single_left]

/-- Every entry of a field of the coefficient space is locally integrable. -/
theorem locallyIntegrable_entry (a : CoeffSpace d) (i j : Fin d) :
    LocallyIntegrable (fun x => (a.1 x) i j) volume := by
  have hmeas : AEStronglyMeasurable (fun x => ((a.1 : Vec d → Mat d) x) i j) volume :=
    (continuous_id.matrix_elem i j).comp_aestronglyMeasurable a.1.aestronglyMeasurable
  rw [MeasureTheory.locallyIntegrable_iff]
  intro K hK
  obtain ⟨M, -, hM⟩ := ae_abs_entry_le_of_aeUniformlyEllipticField a.2 hK.isBounded
  haveI : IsFiniteMeasure (volume.restrict K) :=
    ⟨by rw [Measure.restrict_apply_univ]; exact hK.measure_lt_top⟩
  refine (integrable_const M).mono' hmeas.restrict ?_
  filter_upwards [ae_restrict_of_ae hM, ae_restrict_mem hK.measurableSet] with x hx hxK
  simpa [Real.norm_eq_abs] using hx hxK i j

theorem integrable_entry_mul (a : CoeffSpace d) (i j : Fin d) {φ : Vec d → ℝ}
    (hφ : IsLocalTest (Set.univ : Set (Vec d)) φ) :
    Integrable (fun x => (a.1 x) j i * φ x) volume := by
  have h := integrable_coeffPairing_integrand (Pi.single i (1 : ℝ)) (Pi.single j (1 : ℝ)) hφ a
  simpa [matVecMul_single, vecDot_single_left] using h

/-! ## Singletons are measurable -/

theorem measurableSet_coeffPairing_eq (e e' : Vec d) {φ : Vec d → ℝ}
    (hφ : IsLocalTest (Set.univ : Set (Vec d)) φ) (c : ℝ) :
    MeasurableSet {a : CoeffSpace d | coeffPairing e e' φ a = c} :=
  MeasurableSpace.measurableSet_generateFrom
    ⟨e, e', φ, hφ, {c}, measurableSet_singleton c, rfl⟩

/-- **The mollifier statistics determine the field.**  Two coefficient fields
with the same mollifier statistics at every scale and every point of a dense set
are equal. -/
theorem eq_of_forall_mollifierTest_pairing_eq {a b : CoeffSpace d} {Q : Set (Vec d)}
    (hQ : Dense Q)
    (h : ∀ (i j : Fin d) (n : ℕ), ∀ q ∈ Q,
      coeffPairing (Pi.single i 1) (Pi.single j 1) (mollifierTest d n q) a =
        coeffPairing (Pi.single i 1) (Pi.single j 1) (mollifierTest d n q) b) :
    a = b := by
  have hentry : ∀ p : Fin d × Fin d,
      ∀ᵐ x ∂volume, (a.1 x) p.2 p.1 - (b.1 x) p.2 p.1 = 0 := by
    rintro ⟨i, j⟩
    refine ae_eq_zero_of_mollifierTest_eq_zero _
      ((locallyIntegrable_entry a j i).sub (locallyIntegrable_entry b j i)) Q hQ ?_
    intro n q hq
    have hmem := h i j n q hq
    rw [coeffPairing_basis, coeffPairing_basis] at hmem
    have hia := integrable_entry_mul a i j (isLocalTest_mollifierTest (d := d) n q)
    have hib := integrable_entry_mul b i j (isLocalTest_mollifierTest (d := d) n q)
    calc ∫ y, mollifierTest d n q y * ((a.1 y) j i - (b.1 y) j i) ∂volume
        = ∫ y, ((a.1 y) j i * mollifierTest d n q y -
            (b.1 y) j i * mollifierTest d n q y) ∂volume :=
          integral_congr_ae (Filter.Eventually.of_forall fun y => by ring)
      _ = (∫ y, (a.1 y) j i * mollifierTest d n q y ∂volume) -
            ∫ y, (b.1 y) j i * mollifierTest d n q y ∂volume := integral_sub hia hib
      _ = 0 := by rw [hmem, sub_self]
  have hall : ∀ᵐ x ∂volume, ∀ p : Fin d × Fin d,
      (a.1 x) p.2 p.1 - (b.1 x) p.2 p.1 = 0 := (ae_all_iff).2 hentry
  apply Subtype.ext
  refine AEEqFun.ext_iff.mpr ?_
  filter_upwards [hall] with x hx
  funext r s
  have hrs := hx (s, r)
  simpa [sub_eq_zero] using hrs

private theorem measurableSet_iInter_coeffPairing_eq (b : CoeffSpace d)
    (Q : Set (Vec d)) [Countable Q] :
    MeasurableSet (⋂ p : Fin d × Fin d × ℕ × Q,
      {a : CoeffSpace d |
        coeffPairing (Pi.single p.1 1) (Pi.single p.2.1 1)
            (mollifierTest d p.2.2.1 p.2.2.2) a =
          coeffPairing (Pi.single p.1 1) (Pi.single p.2.1 1)
            (mollifierTest d p.2.2.1 p.2.2.2) b}) :=
  MeasurableSet.iInter fun p =>
    measurableSet_coeffPairing_eq (Pi.single p.1 1) (Pi.single p.2.1 1)
      (isLocalTest_mollifierTest (d := d) p.2.2.1 (p.2.2.2 : Vec d))
      (coeffPairing (Pi.single p.1 1) (Pi.single p.2.1 1)
        (mollifierTest d p.2.2.1 p.2.2.2) b)

private theorem singleton_eq_iInter_coeffPairing_eq (b : CoeffSpace d)
    {Q : Set (Vec d)} (hQ : Dense Q) :
    ({b} : Set (CoeffSpace d)) = ⋂ p : Fin d × Fin d × ℕ × Q,
      {a : CoeffSpace d |
        coeffPairing (Pi.single p.1 1) (Pi.single p.2.1 1)
            (mollifierTest d p.2.2.1 p.2.2.2) a =
          coeffPairing (Pi.single p.1 1) (Pi.single p.2.1 1)
            (mollifierTest d p.2.2.1 p.2.2.2) b} := by
  refine Set.Subset.antisymm (fun a ha => ?_) (fun a ha => ?_)
  · rw [Set.mem_singleton_iff] at ha
    subst ha
    exact Set.mem_iInter.2 fun _ => rfl
  · rw [Set.mem_singleton_iff]
    refine eq_of_forall_mollifierTest_pairing_eq hQ fun i j n q hq => ?_
    exact Set.mem_iInter.1 ha (i, j, n, ⟨q, hq⟩)

/-- **The global sigma-field separates points**: every singleton of the
coefficient space is measurable.  Without this, `e.coarse.ellipticity` could
not be verified on any concrete law, because an almost sure statement under an
atomic law would be untestable. -/
theorem measurableSet_singleton_coeffSpace (b : CoeffSpace d) :
    MeasurableSet ({b} : Set (CoeffSpace d)) := by
  obtain ⟨Q, hQc, hQd⟩ := TopologicalSpace.exists_countable_dense (Vec d)
  haveI := hQc.to_subtype
  rw [singleton_eq_iInter_coeffPairing_eq b hQd]
  exact measurableSet_iInter_coeffPairing_eq b Q

instance instMeasurableSingletonClassCoeffSpace :
    MeasurableSingletonClass (CoeffSpace d) :=
  ⟨measurableSet_singleton_coeffSpace⟩

/-- A local sigma-field is coarser than the global one. -/
theorem coeffSigma_le_global (d : ℕ) (U : Set (Vec d)) :
    coeffSigma d U ≤ instMeasurableSpaceCoeffSpace d := by
  apply MeasurableSpace.generateFrom_le
  rintro s ⟨e, e', φ, hφ, t, ht, rfl⟩
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨e, e', φ, ⟨hφ.contDiff, hφ.hasCompactSupport, Set.subset_univ _⟩, t, ht, rfl⟩

end

end HighContrast
end Homogenization
