/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Provider.Response.CenteredResponseOrder

/-!
# The exact centered-response trace identity

The combined primal--adjoint response at a response-adapted unit load is a
quadratic form in that unit vector.  Summing it over the standard basis gives
exactly `trace X + 2 * trace Y`.
-/

namespace Homogenization.HighContrast.Response

open Book.Ch02 MeasureTheory

open scoped Matrix MatrixOrder Matrix.Norms.L2Operator

noncomputable section

variable {d : ℕ}

/-- The primal--adjoint response sum at the response-adapted load generated by
`e`. -/
def centeredResponseTraceValue (P : Measure (CoeffSpace d)) (U : Domain d)
    (S SStar K : Mat d) (e : Vec d) : ℝ :=
  let p := centeredResponseLoadP S SStar K e
  let q := centeredResponseLoadQ S SStar K e
  centeredResponse P U p (q - responseSkew K *ᵥ p) +
    centeredAdjointResponse P U p (q + responseSkew K *ᵥ p)

/-- The matrix whose quadratic form is the response sum. -/
def centeredResponseTraceMatrix (S SStar K : Mat d) : Mat d :=
  let m := centeredResponseMetric S SStar K
  let r := responseSymmetric K
  matSqrt m⁻¹ * (S * SStar⁻¹ - 1) * matSqrt m +
    matSqrt m⁻¹ * rᴴ *
      (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) * matSqrt m

private theorem trace_invSqrt_mul_mul_sqrt {m : Mat d} (hm : m.PosDef)
    (A : Mat d) :
    Matrix.trace (matSqrt m⁻¹ * A * matSqrt m) = Matrix.trace A := by
  rw [Matrix.trace_mul_cycle, matSqrt_mul_matSqrt_inv hm, Matrix.one_mul]

private theorem sum_single_quadratic (A : Mat d) :
    ∑ i : Fin d, (Pi.single i (1 : ℝ) : Vec d) ⬝ᵥ
      A *ᵥ (Pi.single i (1 : ℝ) : Vec d) = Matrix.trace A := by
  simp [Matrix.trace, Matrix.diag, Matrix.mulVec, dotProduct, Pi.single_apply,
    mul_ite, Finset.sum_ite_eq']

/-- The response sum is the quadratic form of
`centeredResponseTraceMatrix`. -/
theorem centeredResponseTraceValue_eq_quadratic
    {P : Measure (CoeffSpace d)} [IsProbabilityMeasure P] (U : Domain d)
    (hint : HasIntegrableCoarseBlock P (U : Set (Vec d)))
    {S SStar K : Mat d} (hS : S.PosDef) (hStar : SStar.PosDef)
    (hE : toFullBlockMat (annealedBlock P (U : Set (Vec d))) =
      schurBlock S SStar K) (e : Vec d) :
    centeredResponseTraceValue P U S SStar K e =
      e ⬝ᵥ centeredResponseTraceMatrix S SStar K *ᵥ e := by
  let m : Mat d := centeredResponseMetric S SStar K
  let r : Mat d := responseSymmetric K
  let p : Vec d := matSqrt m⁻¹ *ᵥ e
  let q : Vec d := matSqrt m *ᵥ e
  have hcomb := centeredResponse_add_adjoint_eq_schur U hint hS hStar hE
    p q (responseSkew K *ᵥ p)
  have hw : K *ᵥ p - responseSkew K *ᵥ p = r *ᵥ p := by
    rw [← Matrix.sub_mulVec, sub_responseSkew]
  rw [hw] at hcomb
  have hm : m.PosDef := by
    exact centeredResponseMetric_posDef hS hStar K
  have hmi : (matSqrt m⁻¹)ᵀ = matSqrt m⁻¹ := by
    rw [← conjTranspose_eq_transpose']
    exact (matSqrt_spec hm.inv.posSemidef).1.isHermitian
  have hfirst :
      p ⬝ᵥ (S * SStar⁻¹ - 1) *ᵥ q =
        e ⬝ᵥ
          (matSqrt m⁻¹ * (S * SStar⁻¹ - 1) * matSqrt m) *ᵥ e := by
    simp only [p, q, Matrix.mulVec_mulVec]
    rw [dotProduct_mulVec_pair (matSqrt m⁻¹)
      ((S * SStar⁻¹ - 1) * matSqrt m) e e, hmi]
    simp only [Matrix.mul_assoc]
  have hsecond :
      (r *ᵥ p) ⬝ᵥ
          (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) *ᵥ q =
        e ⬝ᵥ
          (matSqrt m⁻¹ * rᴴ *
            (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) * matSqrt m) *ᵥ e := by
    simp only [p, q, Matrix.mulVec_mulVec]
    rw [dotProduct_mulVec_pair (r * matSqrt m⁻¹)
      ((SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) * matSqrt m) e e]
    rw [Matrix.transpose_mul, hmi, ← conjTranspose_eq_transpose' r]
    simp only [Matrix.mul_assoc]
  rw [centeredResponseTraceValue]
  change centeredResponse P U p (q - responseSkew K *ᵥ p) +
      centeredAdjointResponse P U p (q + responseSkew K *ᵥ p) = _
  rw [hcomb, hfirst, hsecond, centeredResponseTraceMatrix]
  simp only [m, r, Matrix.add_mulVec, dotProduct_add]

/-- The trace matrix has trace `trace X + 2 trace Y`. -/
theorem trace_centeredResponseTraceMatrix
    {S SStar : Mat d} (hS : S.PosDef) (hStar : SStar.PosDef) (K : Mat d) :
    Matrix.trace (centeredResponseTraceMatrix S SStar K) =
      Matrix.trace (centeredResponseX S SStar) +
        2 * Matrix.trace (centeredResponseY SStar K) := by
  let m : Mat d := centeredResponseMetric S SStar K
  let r : Mat d := responseSymmetric K
  have hm : m.PosDef := centeredResponseMetric_posDef hS hStar K
  have hfirst := trace_invSqrt_mul_mul_sqrt hm (S * SStar⁻¹ - 1)
  have hsecond := trace_invSqrt_mul_mul_sqrt hm
    (rᴴ * (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹))
  have htwo : K + Kᴴ = (2 : ℝ) • r := by
    rw [← two_smul_responseSymmetric]
  have hr : rᴴ = r := by
    exact responseSymmetric_isHermitian K
  have hmat :
      rᴴ * (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) =
        (2 : ℝ) • (r * SStar⁻¹ * r * SStar⁻¹) := by
    rw [htwo, hr, Matrix.mul_smul, Matrix.smul_mul]
    noncomm_ring
  have hRstar : matSqrt SStar⁻¹ * matSqrt SStar⁻¹ = SStar⁻¹ :=
    (matSqrt_spec hStar.inv.posSemidef).2
  have htraceX : Matrix.trace (centeredResponseX S SStar) =
      Matrix.trace (S * SStar⁻¹ - 1) := by
    rw [centeredResponseX, Matrix.trace_sub, Matrix.trace_sub]
    congr 1
    rw [Matrix.trace_mul_cycle, hRstar, Matrix.trace_mul_comm]
  have htraceY : Matrix.trace (centeredResponseY SStar K) =
      Matrix.trace (r * SStar⁻¹ * r * SStar⁻¹) := by
    rw [centeredResponseY, show responseSymmetric K = r by rfl, hr]
    rw [show matSqrt SStar⁻¹ * r * SStar⁻¹ * r * matSqrt SStar⁻¹ =
        matSqrt SStar⁻¹ * (r * SStar⁻¹ * r) * matSqrt SStar⁻¹ by noncomm_ring]
    rw [Matrix.trace_mul_cycle, hRstar]
    rw [Matrix.trace_mul_comm]
  rw [centeredResponseTraceMatrix, Matrix.trace_add]
  change
    Matrix.trace (matSqrt m⁻¹ * (S * SStar⁻¹ - 1) * matSqrt m) +
      Matrix.trace
        (matSqrt m⁻¹ * rᴴ *
          (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) * matSqrt m) = _
  rw [hfirst]
  have hsecond' :
      Matrix.trace
          (matSqrt m⁻¹ * rᴴ *
            (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) * matSqrt m) =
        Matrix.trace (rᴴ * (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹)) := by
    rw [show matSqrt m⁻¹ * rᴴ *
          (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹) * matSqrt m =
        matSqrt m⁻¹ *
          (rᴴ * (SStar⁻¹ * (K + Kᴴ) * SStar⁻¹)) * matSqrt m by
      noncomm_ring]
    exact hsecond
  rw [hsecond', hmat, Matrix.trace_smul, smul_eq_mul,
    ← htraceX, ← htraceY]

/-- The exact standard-basis sum of the response values. -/
theorem sum_centeredResponseTraceValue
    {P : Measure (CoeffSpace d)} [IsProbabilityMeasure P] (U : Domain d)
    (hint : HasIntegrableCoarseBlock P (U : Set (Vec d)))
    {S SStar K : Mat d} (hS : S.PosDef) (hStar : SStar.PosDef)
    (hE : toFullBlockMat (annealedBlock P (U : Set (Vec d))) =
      schurBlock S SStar K) :
    ∑ i : Fin d, centeredResponseTraceValue P U S SStar K
        (Pi.single i (1 : ℝ)) =
      Matrix.trace (centeredResponseX S SStar) +
        2 * Matrix.trace (centeredResponseY SStar K) := by
  simp_rw [centeredResponseTraceValue_eq_quadratic U hint hS hStar hE]
  rw [sum_single_quadratic, trace_centeredResponseTraceMatrix hS hStar]

end

end Homogenization.HighContrast.Response
