/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Analytic.OptimizerGradientReadout
import HCPoly.Provider.Recurrence.CellMuMeasurability
import HCPoly.Geometry.CoarseSchurBridge

/-!
# Sample measurability of the weighted optimizer state readouts

The sigma-field of the coefficient space is the global one generated by the
smooth linear statistics.  This file carries the weighted coordinate readouts of
the doubled response optimizer state to that sigma-field, on every bounded open cell
of positive volume.

The route is the one the coarse-grained energy already uses.  A field of the
coefficient space is represented, up to a null set, by a field of the exact
coarse source, and the representative map is measurable; the readout only sees
the almost everywhere class of the field, so the value is unchanged.  Every
coarse-source field is almost everywhere uniformly elliptic on the cell, so it
carries a coefficient object there, and it lies in one of the countably many
quantitative ellipticity slices; the slice events are measurable, and on each
slice the readout is measurable by the Galerkin selection.  Gluing the slices
and composing with the representative map gives the statement on the coefficient
space.
-/

namespace Homogenization
namespace HighContrast
namespace Selection

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-! ## The readout as a function of the coefficient object -/

/-- The weighted coordinate readout of the doubled optimizer state. -/
def optimizerStateReadout (U : Book.Ch02.Domain d) (aU : Book.Ch02.CoeffOn U)
    (p q : Vec d) (alpha : BlockCoord d) (eta : Vec d → ℝ) : ℝ :=
  ∫ x in (U : Set (Vec d)), eta x *
    toFullBlockVec (optimizerBlockState U aU p q x) alpha ∂volume

/-- **The readout only sees the almost everywhere class of the coefficient
field.**  Two coefficient objects that agree almost everywhere on the cell have
response optimizers with the same gradient almost everywhere, hence the same
doubled state almost everywhere and the same weighted readouts. -/
theorem optimizerStateReadout_congr {U : Book.Ch02.Domain d}
    {aU bU : Book.Ch02.CoeffOn U} (h : Book.Ch02.CoeffOn.AEEq aU bU)
    (p q : Vec d) (alpha : BlockCoord d) (eta : Vec d → ℝ) :
    optimizerStateReadout U aU p q alpha eta = optimizerStateReadout U bU p q alpha eta := by
  have hgrad := Book.Ch02.canonicalMaximizer_sameGradientAE_ofAEEq h p q
  refine integral_congr_ae ?_
  filter_upwards [hgrad, h] with x hx hax
  have hx' :
      (Book.Ch02.canonicalMaximizer (Book.Ch02.responseExistenceTheory U aU) p
        q).toSolution.toH1.grad x =
      (Book.Ch02.canonicalMaximizer (Book.Ch02.responseExistenceTheory U bU) p
        q).toSolution.toH1.grad x := hx
  have hstate : optimizerBlockState U aU p q x = optimizerBlockState U bU p q x := by
    simp only [optimizerBlockState, hx', hax]
  rw [hstate]

/-! ## The coefficient object carried by a coarse-source field -/

/-- Every coarse-source field is almost everywhere uniformly elliptic on a
bounded cell, with reciprocal constants. -/
theorem exists_srcAEE (U : Book.Ch02.Domain d)
    (hUbdd : IsBoundedDomain (U : Set (Vec d))) (b : Source.Coarse.Carrier d) :
    ∃ eps : ℝ, 0 < eps ∧ IsAEEllipticFieldOn eps eps⁻¹ (U : Set (Vec d)) b.1 :=
  Recurrence.exists_source_isAEEllipticFieldOn U.measurableSet hUbdd b

/-- The normalized lower ellipticity constant of a coarse-source field on the
cell: at most one, so its reciprocal is an upper constant. -/
def srcLam (U : Book.Ch02.Domain d) (hUbdd : IsBoundedDomain (U : Set (Vec d)))
    (b : Source.Coarse.Carrier d) : ℝ :=
  min (exists_srcAEE U hUbdd b).choose 1

theorem srcLam_pos (U : Book.Ch02.Domain d) (hUbdd : IsBoundedDomain (U : Set (Vec d)))
    (b : Source.Coarse.Carrier d) : 0 < srcLam U hUbdd b :=
  lt_min (exists_srcAEE U hUbdd b).choose_spec.1 one_pos

theorem srcLam_le_inv (U : Book.Ch02.Domain d)
    (hUbdd : IsBoundedDomain (U : Set (Vec d))) (b : Source.Coarse.Carrier d) :
    srcLam U hUbdd b ≤ (srcLam U hUbdd b)⁻¹ := by
  have hpos : 0 < srcLam U hUbdd b := srcLam_pos U hUbdd b
  have h1 : srcLam U hUbdd b ≤ 1 := min_le_right _ _
  have h2 : (1 : ℝ) ≤ (srcLam U hUbdd b)⁻¹ := (one_le_inv_iff₀).2 ⟨hpos, h1⟩
  linarith only [h1, h2]

theorem srcLam_isAEElliptic (U : Book.Ch02.Domain d)
    (hUbdd : IsBoundedDomain (U : Set (Vec d))) (b : Source.Coarse.Carrier d) :
    IsAEEllipticFieldOn (srcLam U hUbdd b) (srcLam U hUbdd b)⁻¹
      (U : Set (Vec d)) b.1 := by
  obtain ⟨hUmeas, hmeas, hell⟩ := (exists_srcAEE U hUbdd b).choose_spec.2
  refine ⟨hUmeas, hmeas, ?_⟩
  have hpos : 0 < srcLam U hUbdd b := srcLam_pos U hUbdd b
  have hle : srcLam U hUbdd b ≤ (exists_srcAEE U hUbdd b).choose := min_le_left _ _
  have hinv : ((exists_srcAEE U hUbdd b).choose)⁻¹ ≤ (srcLam U hUbdd b)⁻¹ :=
    inv_anti₀ hpos hle
  filter_upwards [hell] with x hx
  exact hx.mono hpos hle hinv

/-- A coarse-source field, viewed as a coefficient object on a bounded open
cell. -/
def sourceCoeffOn (U : Book.Ch02.Domain d)
    (hUbdd : IsBoundedDomain (U : Set (Vec d))) (b : Source.Coarse.Carrier d) :
    Book.Ch02.CoeffOn U where
  toCoeffField := b.1
  lam := srcLam U hUbdd b
  Lam := (srcLam U hUbdd b)⁻¹
  lam_pos := srcLam_pos U hUbdd b
  lam_le_Lam := srcLam_le_inv U hUbdd b
  aeStronglyMeasurable := (srcLam_isAEElliptic U hUbdd b).2.1
  aeElliptic := (srcLam_isAEElliptic U hUbdd b).2.2

/-- The weighted coordinate readout of a coarse-source field. -/
def sourceOptimizerStateReadout (U : Book.Ch02.Domain d)
    (hUbdd : IsBoundedDomain (U : Set (Vec d))) (p q : Vec d) (alpha : BlockCoord d)
    (eta : Vec d → ℝ) (b : Source.Coarse.Carrier d) : ℝ :=
  optimizerStateReadout U (sourceCoeffOn U hUbdd b) p q alpha eta

/-! ## Measurability on the exact coarse source -/

/-- **The readout is measurable on the exact coarse source**, for the source's
own sigma-field of the cell. -/
theorem measurable_sourceOptimizerStateReadout_local {U : Book.Ch02.Domain d}
    (hUopen : IsOpen (U : Set (Vec d))) (hUbdd : IsBoundedDomain (U : Set (Vec d)))
    (hvol : 0 < (volume (U : Set (Vec d))).toReal)
    (p q : Vec d) (alpha : BlockCoord d) {eta : Vec d → ℝ}
    (heta : MemScalarL2 (U : Set (Vec d)) eta) :
    @Measurable (Source.Coarse.Carrier d) ℝ
      (Source.Coarse.localSigma (U : Set (Vec d)) hUopen.measurableSet) _
      (sourceOptimizerStateReadout U hUbdd p q alpha eta) := by
  classical
  have : IsFiniteMeasure (volumeMeasureOn (U : Set (Vec d))) :=
    hUbdd.isFiniteMeasure_restrict_volume
  have hUfin : volume (U : Set (Vec d)) ≠ ⊤ := ne_of_lt hUbdd.volume_lt_top
  let : MeasurableSpace (Source.Coarse.Carrier d) :=
    Source.Coarse.localSigma (U : Set (Vec d)) hUopen.measurableSet
  set slice : ℕ → Set (Source.Coarse.Carrier d) :=
    fun k => {b | AEEQuantitativeEllipticSlice (U : Set (Vec d)) k b.1} with hslice
  set covered : Set (Source.Coarse.Carrier d) := ⋃ k : ℕ, slice k with hcovered
  set cover : Option ℕ → Set (Source.Coarse.Carrier d) := fun n =>
    match n with
    | none => coveredᶜ
    | some k => slice k with hcoverdef
  set f : (n : Option ℕ) → cover n → ℝ := fun _ b =>
    sourceOptimizerStateReadout U hUbdd p q alpha eta b.1 with hf
  have hagree : ∀ (m n : Option ℕ) (b : Source.Coarse.Carrier d)
      (hbm : b ∈ cover m) (hbn : b ∈ cover n), f m ⟨b, hbm⟩ = f n ⟨b, hbn⟩ := by
    intro _ _ _ _ _
    rfl
  have hcover : ⋃ n : Option ℕ, cover n = Set.univ := by
    ext b
    refine ⟨fun _ => Set.mem_univ b, fun _ => ?_⟩
    by_cases hb : b ∈ covered
    · rcases Set.mem_iUnion.mp hb with ⟨k, hk⟩
      exact Set.mem_iUnion.mpr ⟨some k, by simpa [hcoverdef] using hk⟩
    · exact Set.mem_iUnion.mpr ⟨none, by simpa [hcoverdef] using hb⟩
  have hcover_meas : ∀ n : Option ℕ, MeasurableSet (cover n) := by
    intro n
    have hk : ∀ k : ℕ, MeasurableSet (slice k) := fun k =>
      Recurrence.measurableSet_sourceLocal_aeeSlice hUopen k
    cases n with
    | none => exact (MeasurableSet.iUnion hk).compl
    | some k => exact hk k
  have hfm : ∀ n : Option ℕ, Measurable (f n) := by
    intro n
    cases n with
    | none =>
        have hzero : f none = fun _ : cover none => (0 : ℝ) := by
          funext b
          exact absurd (Set.mem_iUnion.mpr
            (Recurrence.exists_source_aeeQuantitativeEllipticSlice hUopen.measurableSet hUbdd
              (b : Source.Coarse.Carrier d))) b.2
        rw [hzero]
        exact measurable_const
    | some k =>
        have hEntry : ∀ (i' j' : Fin d) {φ : Vec d → ℝ}, ContDiff ℝ (⊤ : ℕ∞) φ →
            HasCompactSupport φ → tsupport φ ⊆ (U : Set (Vec d)) →
            Measurable fun x : cover (some k) =>
              entryTestR i' j' φ
                (Source.Coarse.coarseToRegular (x : Source.Coarse.Carrier d)) := by
          intro i' j' φ hcont hcpt hsupp
          have hentry : @Measurable (RegCoeffField d) ℝ
              (SmoothLocalSigmaR (U : Set (Vec d))) _ (entryTestR i' j' φ) := by
            intro t ht
            exact MeasurableSpace.measurableSet_generateFrom
              ⟨i', j', φ, hcont, hcpt, hsupp, t, ht, rfl⟩
          exact hentry.comp
            ((Source.Coarse.measurable_coarseToRegular_smoothLocal (U : Set (Vec d))
              hUopen.measurableSet).comp measurable_subtype_coe)
        exact measurable_integral_weighted_optimizerBlockState hUopen hUfin hvol
          (A := fun x : cover (some k) =>
            Source.Coarse.coarseToRegular (x : Source.Coarse.Carrier d))
          (fun x => x.2) hEntry
          (fun x => sourceCoeffOn U hUbdd (x : Source.Coarse.Carrier d))
          (fun _ => rfl) p q alpha heta
  have hEq : sourceOptimizerStateReadout U hUbdd p q alpha eta =
      Set.liftCover cover f hagree hcover := by
    funext b
    obtain ⟨k, hbk⟩ :=
      Recurrence.exists_source_aeeQuantitativeEllipticSlice hUopen.measurableSet hUbdd b
    have hmem : b ∈ cover (some k) := hbk
    rw [Set.liftCover_of_mem (S := cover) (f := f) (hf := hagree) (hS := hcover)
      (i := some k) hmem]
  rw [hEq]
  exact measurable_liftCover cover hcover_meas f hfm hagree hcover

/-- The readout is measurable on the exact coarse source for its global
sigma-field. -/
theorem measurable_sourceOptimizerStateReadout {U : Book.Ch02.Domain d}
    (hUopen : IsOpen (U : Set (Vec d))) (hUbdd : IsBoundedDomain (U : Set (Vec d)))
    (hvol : 0 < (volume (U : Set (Vec d))).toReal)
    (p q : Vec d) (alpha : BlockCoord d) {eta : Vec d → ℝ}
    (heta : MemScalarL2 (U : Set (Vec d)) eta) :
    Measurable (sourceOptimizerStateReadout U hUbdd p q alpha eta) :=
  Measurable.mono
    (measurable_sourceOptimizerStateReadout_local hUopen hUbdd hvol p q alpha heta)
    (Source.Coarse.localSigma_mono hUopen.measurableSet MeasurableSet.univ
      (Set.subset_univ _)) le_rfl

/-! ## Measurability on the coefficient space -/

/-- **The weighted coordinate readout of the doubled optimizer state is
measurable on the coefficient space**, for the global sigma-field generated by
the smooth linear statistics, on every bounded open cell of positive volume. -/
theorem measurable_optimizerStateReadout_coeffSpace {U : Book.Ch02.Domain d}
    (hUopen : IsOpen (U : Set (Vec d))) (hUbdd : IsBoundedDomain (U : Set (Vec d)))
    (hvol : 0 < (volume (U : Set (Vec d))).toReal)
    (p q : Vec d) (alpha : BlockCoord d) {eta : Vec d → ℝ}
    (heta : MemScalarL2 (U : Set (Vec d)) eta) :
    Measurable fun a : CoeffSpace d => optimizerStateReadout U (a.coeffOn U) p q alpha eta := by
  have hEq : (fun a : CoeffSpace d => optimizerStateReadout U (a.coeffOn U) p q alpha eta) =
      sourceOptimizerStateReadout U hUbdd p q alpha eta ∘ sourceRepresentative := by
    funext a
    refine optimizerStateReadout_congr ?_ p q alpha eta
    exact ae_restrict_of_ae (sourceRepresentative_ae_eq a)
  rw [hEq]
  exact (measurable_sourceOptimizerStateReadout hUopen hUbdd hvol p q alpha heta).comp
    measurable_sourceRepresentative

end

end Selection
end HighContrast
end Homogenization
