/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Setup.LocalSigmaFields
import Homogenization.Probability.RescaledLaw
import Mathlib.MeasureTheory.Measure.Haar.NormedSpace

/-!
# Triadic dilation on the coefficient space

The coefficient-space dilation reads a sample at the points `3^n x`.  It is
defined directly on the almost-everywhere quotient, preserves the field's own
ellipticity constants, and is measurable for the sigma-field generated by
smooth compactly supported linear statistics.
-/

namespace Homogenization
namespace HighContrast
namespace CoeffSpace

open MeasureTheory
open scoped Pointwise

noncomputable section

variable {d : ℕ}

private theorem quasiMeasurePreserving_const_smul (r : ℝ) (hr : r ≠ 0) :
    Measure.QuasiMeasurePreserving (fun x : Vec d => r • x) volume volume :=
  Measure.quasiMeasurePreserving_smul volume hr

private noncomputable def scalarPullback (r : ℝ) (hr : r ≠ 0)
    (a : CoeffSpace d) : CoeffSpace d where
  val := a.1.compQuasiMeasurePreserving (fun x : Vec d => r • x)
    (quasiMeasurePreserving_const_smul r hr)
  property := by
    intro R hR
    have hRpos : (0 : ℝ) < |r| * R + R := by
      have h1 : (0 : ℝ) ≤ |r| * R := mul_nonneg (abs_nonneg r) hR.le
      linarith only [h1, hR]
    obtain ⟨lam, Lam, hlam, hle, hell⟩ := a.2 (|r| * R + R) hRpos
    refine ⟨lam, Lam, hlam, hle, ?_⟩
    filter_upwards
      [(quasiMeasurePreserving_const_smul (d := d) r hr).tendsto_ae hell,
        a.1.coeFn_compQuasiMeasurePreserving
          (quasiMeasurePreserving_const_smul (d := d) r hr)] with x hx hrep hxb
    rw [hrep]
    refine hx (mem_ball_zero_iff.2 ?_)
    have hxn : ‖x‖ < R := mem_ball_zero_iff.1 hxb
    rw [norm_smul, Real.norm_eq_abs]
    calc |r| * ‖x‖ ≤ |r| * R := mul_le_mul_of_nonneg_left hxn.le (abs_nonneg r)
      _ < |r| * R + R := by linarith only [hR]

private theorem scalarPullback_ae (r : ℝ) (hr : r ≠ 0) (a : CoeffSpace d) :
    (⇑(scalarPullback r hr a).1 : CoeffField d) =ᵐ[volume]
      fun x => a.1 (r • x) := by
  unfold scalarPullback
  simpa [Function.comp_def] using
    a.1.coeFn_compQuasiMeasurePreserving
      (quasiMeasurePreserving_const_smul (d := d) r hr)

/-- Pull a coefficient sample back by the triadic dilation `x ↦ 3^n x`. -/
noncomputable def triadicDilation (n : ℕ) (a : CoeffSpace d) : CoeffSpace d :=
  scalarPullback ((3 : ℝ) ^ n) (by positivity) a

/-- The inverse carrier map to `triadicDilation n`. -/
noncomputable def triadicContraction (n : ℕ) (a : CoeffSpace d) : CoeffSpace d :=
  scalarPullback (((3 : ℝ) ^ n)⁻¹) (by positivity) a

/-- The quotient dilation has the expected representative almost everywhere. -/
theorem triadicDilation_ae (n : ℕ) (a : CoeffSpace d) :
    (⇑(triadicDilation n a).1 : CoeffField d) =ᵐ[volume]
      fun x => a.1 (triadicDilateVec n x) := by
  simpa [triadicDilation, triadicDilateVec, Pi.smul_apply, smul_eq_mul] using
    scalarPullback_ae ((3 : ℝ) ^ n) (by positivity) a

/-- The inverse quotient dilation reads the sample at `3⁻ⁿ x`. -/
theorem triadicContraction_ae (n : ℕ) (a : CoeffSpace d) :
    (⇑(triadicContraction n a).1 : CoeffField d) =ᵐ[volume]
      fun x => a.1 (((3 : ℝ) ^ n)⁻¹ • x) := by
  simpa [triadicContraction] using
    scalarPullback_ae (((3 : ℝ) ^ n)⁻¹) (by positivity) a

/-- Contracting a dilated quotient sample recovers the sample. -/
@[simp] theorem triadicContraction_triadicDilation (n : ℕ) (a : CoeffSpace d) :
    triadicContraction n (triadicDilation n a) = a := by
  apply Subtype.ext
  apply AEEqFun.ext
  have hpull :=
    (quasiMeasurePreserving_const_smul (d := d) (((3 : ℝ) ^ n)⁻¹) (by positivity)).tendsto_ae
      (triadicDilation_ae n a)
  filter_upwards [triadicContraction_ae n (triadicDilation n a), hpull]
    with x hleft hright
  change (triadicDilation n a).1 (((3 : ℝ) ^ n)⁻¹ • x) =
    a.1 (triadicDilateVec n (((3 : ℝ) ^ n)⁻¹ • x)) at hright
  rw [hleft, hright]
  congr 1
  change ((3 : ℝ) ^ n) • (((3 : ℝ) ^ n)⁻¹ • x) = x
  rw [smul_smul, mul_inv_cancel₀ (by positivity), one_smul]

/-- Dilating a contracted quotient sample recovers the sample. -/
@[simp] theorem triadicDilation_triadicContraction (n : ℕ) (a : CoeffSpace d) :
    triadicDilation n (triadicContraction n a) = a := by
  apply Subtype.ext
  apply AEEqFun.ext
  have hpull :=
    (quasiMeasurePreserving_const_smul (d := d) ((3 : ℝ) ^ n) (by positivity)).tendsto_ae
      (triadicContraction_ae n a)
  filter_upwards [triadicDilation_ae n (triadicContraction n a), hpull]
    with x hleft hright
  change (triadicContraction n a).1 (triadicDilateVec n x) =
    a.1 (((3 : ℝ) ^ n)⁻¹ • triadicDilateVec n x) at hright
  rw [hleft, hright]
  congr 1
  change ((3 : ℝ) ^ n)⁻¹ • ((3 : ℝ) ^ n • x) = x
  rw [smul_smul, inv_mul_cancel₀ (by positivity), one_smul]

private theorem coeffPairing_scalarPullback (r : ℝ) (hr : 0 < r)
    (e e' : Vec d) (phi : Vec d → ℝ) (a : CoeffSpace d) :
    coeffPairing e e' phi (scalarPullback r hr.ne' a) =
      (r ^ d)⁻¹ * coeffPairing e e' (fun y => phi (r⁻¹ • y)) a := by
  let f : Vec d → ℝ := fun y =>
    vecDot e' (matVecMul (a.1 y) e) * phi (r⁻¹ • y)
  have hcv :
      ∫ x in (Set.univ : Set (Vec d)), f (r • x) ∂volume =
        (r ^ d)⁻¹ • ∫ y in r • (Set.univ : Set (Vec d)), f y ∂volume := by
    simpa [Vec] using
      (Measure.setIntegral_comp_smul_of_pos
        (μ := volume) (f := f) (s := Set.univ) hr)
  have huniv : r • (Set.univ : Set (Vec d)) = Set.univ := by
    ext y
    constructor
    · intro _
      trivial
    · intro _
      refine ⟨r⁻¹ • y, trivial, ?_⟩
      change r • (r⁻¹ • y) = y
      rw [smul_smul, mul_inv_cancel₀ hr.ne', one_smul]
  unfold coeffPairing
  calc
    (∫ x, vecDot e' (matVecMul ((scalarPullback r hr.ne' a).1 x) e) * phi x
        ∂volume) = ∫ x, f (r • x) ∂volume := by
      apply integral_congr_ae
      filter_upwards [scalarPullback_ae r hr.ne' a] with x hx
      rw [hx]
      have hback : r⁻¹ • (r • x) = x := by
        rw [smul_smul, inv_mul_cancel₀ hr.ne', one_smul]
      simp only [f, hback]
    _ = ∫ x in (Set.univ : Set (Vec d)), f (r • x) ∂volume := by simp
    _ = (r ^ d)⁻¹ • ∫ y in r • (Set.univ : Set (Vec d)), f y ∂volume := hcv
    _ = (r ^ d)⁻¹ *
        ∫ y, vecDot e' (matVecMul (a.1 y) e) * phi (r⁻¹ • y) ∂volume := by
      simp [f, huniv]

private theorem isLocalTest_inv_smul (r : ℝ) (hr : 0 < r)
    {phi : Vec d → ℝ} (hphi : IsLocalTest Set.univ phi) :
    IsLocalTest Set.univ (fun y => phi (r⁻¹ • y)) := by
  refine ⟨by
      simpa [Function.comp_def] using hphi.contDiff.comp (contDiff_const_smul r⁻¹), ?_,
    Set.subset_univ _⟩
  show HasCompactSupport (phi ∘ Homeomorph.smulOfNeZero r⁻¹ (inv_ne_zero hr.ne'))
  simpa [Function.comp_def] using
    hphi.hasCompactSupport.comp_homeomorph
      (Homeomorph.smulOfNeZero r⁻¹ (inv_ne_zero hr.ne'))

private theorem measurable_scalarPullback (r : ℝ) (hr : 0 < r) :
    Measurable (scalarPullback r hr.ne' : CoeffSpace d → CoeffSpace d) := by
  change @Measurable (CoeffSpace d) (CoeffSpace d) (coeffSigma d Set.univ)
    (MeasurableSpace.generateFrom
      {s | ∃ (e e' : Vec d) (phi : Vec d → ℝ), IsLocalTest Set.univ phi ∧
        ∃ u : Set ℝ, MeasurableSet u ∧ s = coeffPairing e e' phi ⁻¹' u})
    (scalarPullback r hr.ne')
  apply measurable_generateFrom
  rintro s ⟨e, e', phi, hphi, u, hu, rfl⟩
  let psi : Vec d → ℝ := fun y => phi (r⁻¹ • y)
  let c : ℝ := (r ^ d)⁻¹
  let u' : Set ℝ := (fun z : ℝ => c * z) ⁻¹' u
  have hu' : MeasurableSet u' :=
    hu.preimage ((continuous_const.mul continuous_id).measurable)
  have hpsi : IsLocalTest Set.univ psi := isLocalTest_inv_smul r hr hphi
  have hset :
      scalarPullback r hr.ne' ⁻¹' (coeffPairing e e' phi ⁻¹' u) =
        coeffPairing e e' psi ⁻¹' u' := by
    ext a
    change coeffPairing e e' phi (scalarPullback r hr.ne' a) ∈ u ↔ _
    rw [coeffPairing_scalarPullback r hr]
    rfl
  rw [hset]
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨e, e', psi, hpsi, u', hu', rfl⟩

/-- Triadic dilation pulls a generating pairing back to the inverse-dilated
test, with the Jacobian factor made explicit. -/
theorem coeffPairing_triadicDilation (n : ℕ) (e e' : Vec d)
    (phi : Vec d → ℝ) (a : CoeffSpace d) :
    coeffPairing e e' phi (triadicDilation n a) =
      ((((3 : ℝ) ^ n) ^ d)⁻¹) *
        coeffPairing e e' (fun y => phi (((3 : ℝ) ^ n)⁻¹ • y)) a := by
  exact coeffPairing_scalarPullback ((3 : ℝ) ^ n) (by positivity) e e' phi a

private theorem isLocalTest_triadicPullback (n : ℕ) {U : Set (Vec d)}
    {phi : Vec d → ℝ} (hphi : IsLocalTest U phi) :
    IsLocalTest (triadicDilateSet n U)
      (fun y => phi (((3 : ℝ) ^ n)⁻¹ • y)) := by
  let r : ℝ := (3 : ℝ) ^ n
  have hr : 0 < r := by positivity
  refine ⟨by
      simpa [Function.comp_def] using hphi.contDiff.comp (contDiff_const_smul r⁻¹), ?_, ?_⟩
  · show HasCompactSupport (phi ∘ Homeomorph.smulOfNeZero r⁻¹ (inv_ne_zero hr.ne'))
    simpa [Function.comp_def] using
      hphi.hasCompactSupport.comp_homeomorph
        (Homeomorph.smulOfNeZero r⁻¹ (inv_ne_zero hr.ne'))
  · intro y hy
    have hy' : r⁻¹ • y ∈ tsupport phi := by
      rw [show (fun y : Vec d => phi (r⁻¹ • y)) =
          phi ∘ Homeomorph.smulOfNeZero r⁻¹ (inv_ne_zero hr.ne') by rfl,
        tsupport_comp_eq_preimage] at hy
      exact hy
    refine ⟨r⁻¹ • y, hphi.tsupport_subset hy', ?_⟩
    change y = r • (r⁻¹ • y)
    rw [smul_smul, mul_inv_cancel₀ hr.ne', one_smul]

/-- Pullback by triadic dilation is measurable from the local sigma-field on
the dilated region to the local sigma-field on the original region. -/
theorem measurable_triadicDilation_coeffSigma (n : ℕ) (U : Set (Vec d)) :
    @Measurable (CoeffSpace d) (CoeffSpace d)
      (coeffSigma d (triadicDilateSet n U)) (coeffSigma d U)
      (triadicDilation n) := by
  rw [measurable_iff_comap_le, coeffSigma, coeffSigma,
    MeasurableSpace.comap_generateFrom]
  apply MeasurableSpace.generateFrom_le
  rintro s ⟨t, ⟨e, e', phi, hphi, u, hu, rfl⟩, rfl⟩
  let psi : Vec d → ℝ := fun y => phi (((3 : ℝ) ^ n)⁻¹ • y)
  let c : ℝ := (((3 : ℝ) ^ n) ^ d)⁻¹
  let u' : Set ℝ := (fun z : ℝ => c * z) ⁻¹' u
  have hu' : MeasurableSet u' :=
    hu.preimage ((continuous_const.mul continuous_id).measurable)
  have hpsi : IsLocalTest (triadicDilateSet n U) psi :=
    isLocalTest_triadicPullback n hphi
  change @MeasurableSet (CoeffSpace d) (coeffSigma d (triadicDilateSet n U))
    ((fun a : CoeffSpace d => coeffPairing e e' phi (triadicDilation n a)) ⁻¹' u)
  have hfun : (fun a : CoeffSpace d => coeffPairing e e' phi (triadicDilation n a)) =
      fun a => c * coeffPairing e e' psi a := by
    funext a
    exact coeffPairing_triadicDilation n e e' phi a
  rw [hfun]
  change @MeasurableSet (CoeffSpace d) (coeffSigma d (triadicDilateSet n U))
    (coeffPairing e e' psi ⁻¹' u')
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨e, e', psi, hpsi, u', hu', rfl⟩

/-- Triadic dilation is measurable for the canonical coefficient sigma-field. -/
theorem measurable_triadicDilation (n : ℕ) :
    Measurable (triadicDilation (d := d) n) :=
  measurable_scalarPullback ((3 : ℝ) ^ n) (by positivity)

/-- The inverse triadic carrier map is measurable. -/
theorem measurable_triadicContraction (n : ℕ) :
    Measurable (triadicContraction (d := d) n) :=
  measurable_scalarPullback (((3 : ℝ) ^ n)⁻¹) (by positivity)

/-- Triadic dilation is a measurable equivalence of the coefficient space. -/
noncomputable def triadicDilationMeasurableEquiv (n : ℕ) :
    CoeffSpace d ≃ᵐ CoeffSpace d where
  toEquiv :=
    { toFun := triadicDilation n
      invFun := triadicContraction n
      left_inv := triadicContraction_triadicDilation n
      right_inv := triadicDilation_triadicContraction n }
  measurable_toFun := measurable_triadicDilation n
  measurable_invFun := measurable_triadicContraction n

/-- Integer translation after dilation is the dilation of the correspondingly
rescaled integer translation. -/
theorem translateCoeff_triadicDilation (n : ℕ) (z : Fin d → ℤ)
    (a : CoeffSpace d) :
    translateCoeff z (triadicDilation n a) =
      triadicDilation n (translateCoeff (triadicScaleIntShift n z) a) := by
  apply Subtype.ext
  apply AEEqFun.ext
  have hshift :=
    (measurePreserving_add_right (volume : Measure (Vec d))
      (Source.AKL.intTranslation z)).quasiMeasurePreserving.tendsto_ae
        (triadicDilation_ae n a)
  have hsource :=
    (quasiMeasurePreserving_const_smul (d := d) ((3 : ℝ) ^ n) (by positivity)).tendsto_ae
      (Source.AKL.translateField_ae (triadicScaleIntShift n z) a.1)
  filter_upwards
    [Source.AKL.translateField_ae z (triadicDilation n a).1, hshift,
      triadicDilation_ae n (translateCoeff (triadicScaleIntShift n z) a), hsource]
      with x hleft hdilated hright htranslated
  change (triadicDilation n a).1 (x + Source.AKL.intTranslation z) =
    a.1 (triadicDilateVec n (x + Source.AKL.intTranslation z)) at hdilated
  change (translateCoeff (triadicScaleIntShift n z) a).1 (triadicDilateVec n x) =
    a.1 (triadicDilateVec n x +
      Source.AKL.intTranslation (triadicScaleIntShift n z)) at htranslated
  change (Source.AKL.translateField z (triadicDilation n a).1) x =
    (triadicDilation n (translateCoeff (triadicScaleIntShift n z) a)).1 x
  rw [hleft, hdilated, hright, htranslated]
  congr 1
  funext i
  simp only [triadicDilateVec, Source.AKL.intTranslation, triadicScaleIntShift,
    Pi.add_apply]
  push_cast
  ring

end

end CoeffSpace
end HighContrast
end Homogenization
