/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Geometry.GeometricMean
import HCPoly.Provider.Quenched.UnitRangeBlockCutoff
import HCPoly.Provider.Quenched.UnitRangeSubadditivity
import HCPoly.Provider.Recurrence.AdaptedColourIndependence
import HCPoly.Provider.Recurrence.PositiveGapClosure
import HCPoly.Provider.Sharp.CoarseBlockPositivity

/-!
# The normalized local block cutoff

The one-step ellipticity renormalization is applied after conjugating every
local coarse response by the inverse square root of its deterministic annealed
mean.  This file supplies the locality, integrability, and mean-order facts for
the hard whole-block cutoff in those normalized coordinates.
-/

namespace Homogenization
namespace HighContrast
namespace Quenched

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-- The entries of a normalized standard-cell response are measurable for the
sigma-field generated by that cell. -/
theorem measurable_blockMatEntry_normalizedBlock_coarseBlock_standardCell
    (F : BlockMat d) (k : ℤ) (w : Fin d → ℤ) (α β : BlockCoord d) :
    @Measurable (CoeffSpace d) ℝ (coeffSigma d (standardCell d k w)) _
      (fun a => blockMatEntry
        (normalizedBlock (coarseBlock (standardCell d k w) a) F) α β) := by
  letI : MeasurableSpace (CoeffSpace d) := coeffSigma d (standardCell d k w)
  have hentry : ∀ γ δ : BlockCoord d,
      Measurable fun a : CoeffSpace d =>
        blockMatEntry (coarseBlock (standardCell d k w) a) γ δ :=
    fun γ δ => measurable_blockMatEntry_coarseBlock_standardCell k w γ δ
  have hfun : (fun a : CoeffSpace d => blockMatEntry
        (normalizedBlock (coarseBlock (standardCell d k w) a) F) α β) =
      fun a : CoeffSpace d => ∑ γ : BlockCoord d, ∑ δ : BlockCoord d,
        matSqrt ((toFullBlockMat F)⁻¹) α δ *
          blockMatEntry (coarseBlock (standardCell d k w) a) δ γ *
          matSqrt ((toFullBlockMat F)⁻¹) γ β := by
    funext a
    rw [← toFullBlockMat_eq_blockMatEntry,
      Recurrence.toFullBlockMat_normalizedBlock_apply]
    exact Finset.sum_congr rfl fun γ _ => Finset.sum_congr rfl fun δ _ => by
      rw [toFullBlockMat_eq_blockMatEntry]
  rw [hfun]
  exact Finset.measurable_sum _ fun γ _ => Finset.measurable_sum _ fun δ _ =>
    ((hentry δ γ).const_mul _).mul_const _

/-! ## Stationary identification of the normalizing mean -/

end

end Quenched
end HighContrast
end Homogenization
