/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Provider.Recurrence.AdaptedCellPositivity
import HCPoly.Provider.Recurrence.CellSliceMeasurability
import HCPoly.Provider.Recurrence.DomainMuMeasurability
import Homogenization.Book.Ch04.SourceEllipticity

/-!
# The measurability of the coarse block on a bounded open cell

The coarse-grained energy of a bounded open cell of positive volume is
measurable in the coefficient field, for the sigma-field the coefficient space
carries — the global one generated by the smooth linear statistics.  This is the
measurability half of the first of the coarse-block properties taken from HC,
and with it the whole clause holds on the adapted cells `⋄_j^q` and their aligned
translates.

The argument has three moves.  A field of the coefficient space is represented,
up to a null set, by a field of the exact coarse source, and the representative
map is measurable for the two global sigma-fields; that is already available.
Every coarse-source field is uniformly elliptic on every Euclidean ball, hence on
the bounded cell, so it lies in one of the countably many quantitative
ellipticity slices of the cell; and the slice events are measurable.  On each
slice the coarse-grained energy is measurable, being the infimum of countably
many fixed competitor energies.  Gluing the slices gives measurability on the
whole source, and composing with the representative map brings it back to the
coefficient space.
-/

namespace Homogenization
namespace HighContrast
namespace Recurrence

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-! ## Every coarse-source field lies in a slice of a bounded cell -/

/-- A bounded cell is contained in a Euclidean ball of radius at least one, the
shape the coarse source's ellipticity data is indexed by. -/
theorem exists_subset_sourceEuclideanBall {U : Set (Vec d)} (hU : IsBoundedDomain U) :
    ∃ R : ℝ, 1 ≤ R ∧ U ⊆ Source.Coarse.euclideanBall R := by
  classical
  let e : Vec d ≃L[ℝ] EuclideanSpace ℝ (Fin d) :=
    (PiLp.continuousLinearEquiv 2 ℝ fun _ : Fin d => ℝ).symm
  refine ⟨max 1 (‖e.toContinuousLinearMap‖ * Classical.choose hU + 1), le_max_left _ _, ?_⟩
  intro x hx
  have hxC : euclideanNorm x ≤ ‖e.toContinuousLinearMap‖ * Classical.choose hU := by
    calc euclideanNorm x = ‖HilbertVec.ofVec x‖ := euclideanNorm_eq_norm_ofVec x
      _ = ‖e x‖ := rfl
      _ ≤ ‖e.toContinuousLinearMap‖ * Classical.choose hU :=
        e.toContinuousLinearMap.le_opNorm_of_le (hU.norm_le_choose hx)
  change euclideanNorm x < max 1 (‖e.toContinuousLinearMap‖ * Classical.choose hU + 1)
  exact hxC.trans_lt ((lt_add_one _).trans_le (le_max_right _ _))

/-- A coarse-source field is almost everywhere uniformly elliptic on every
bounded measurable cell. -/
theorem exists_source_isAEEllipticFieldOn {U : Set (Vec d)} (hUmeas : MeasurableSet U)
    (hUbdd : IsBoundedDomain U) (b : Source.Coarse.Carrier d) :
    ∃ eps : ℝ, 0 < eps ∧ IsAEEllipticFieldOn eps eps⁻¹ U b.1 := by
  classical
  obtain ⟨R, hR, hUR⟩ := exists_subset_sourceEuclideanBall hUbdd
  obtain ⟨eps, heps_pos, -, hEll⟩ := b.2.2 R hR
  have hmeas : Measurable fun x i j => if x ∈ U then b.1 x i j else 0 := by
    refine measurable_pi_iff.2 fun i => measurable_pi_iff.2 fun j => ?_
    have heq : (fun x => if x ∈ U then b.1 x i j else 0)
        = Set.indicator U fun x => b.1 x i j := by
      funext x
      by_cases hx : x ∈ U <;> simp [hx]
    rw [heq]
    exact (b.2.1 i j).indicator hUmeas
  exact ⟨eps, heps_pos,
    IsAEEllipticFieldOn.of_isEllipticFieldOn ⟨hmeas, fun x hx => hEll x (hUR hx)⟩⟩

/-- Every coarse-source field belongs to one of the countably many quantitative
ellipticity slices of a bounded measurable cell. -/
theorem exists_source_aeeQuantitativeEllipticSlice {U : Set (Vec d)}
    (hUmeas : MeasurableSet U) (hUbdd : IsBoundedDomain U) (b : Source.Coarse.Carrier d) :
    ∃ k : ℕ, AEEQuantitativeEllipticSlice U k b.1 := by
  obtain ⟨eps, heps, hEll⟩ := exists_source_isAEEllipticFieldOn hUmeas hUbdd b
  exact AEEQuantitativeEllipticSlice.exists_of_aeeEllipticOn heps hEll

/-! ## The coarse-grained energy is measurable on the coarse source -/

/-- **The coarse-grained energy of a bounded open cell of positive volume is
measurable on the exact coarse source**, for the source's own sigma-field of
that cell.  The slices cover the source and are measurable there, and on each of
them the energy is a countable infimum of fixed competitor energies.  This is
the local form: the energy of a cell sees only the field inside it. -/
theorem measurable_Mu_carrier_local {U : Set (Vec d)} (hUopen : IsOpen U)
    (hUbdd : IsBoundedDomain U) (hvol : 0 < (volume U).toReal) (P0 : BlockVec d) :
    @Measurable (Source.Coarse.Carrier d) ℝ
      (Source.Coarse.localSigma U hUopen.measurableSet) _
      fun b : Source.Coarse.Carrier d => Mu U P0 (b.1 : CoeffField d) := by
  classical
  haveI : IsFiniteMeasure (volumeMeasureOn U) := hUbdd.isFiniteMeasure_restrict_volume
  have hUfin : volume U ≠ ⊤ := ne_of_lt hUbdd.volume_lt_top
  letI : MeasurableSpace (Source.Coarse.Carrier d) :=
    Source.Coarse.localSigma U hUopen.measurableSet
  set slice : ℕ → Set (Source.Coarse.Carrier d) :=
    fun k => {b | AEEQuantitativeEllipticSlice U k b.1} with hslice
  set covered : Set (Source.Coarse.Carrier d) := ⋃ k : ℕ, slice k with hcovered
  set cover : Option ℕ → Set (Source.Coarse.Carrier d) := fun i =>
    match i with
    | none => coveredᶜ
    | some k => slice k with hcoverdef
  set f : (i : Option ℕ) → cover i → ℝ := fun i =>
    match i with
    | none => fun _ => 0
    | some _k => fun b => Mu U P0 (b.1.1 : CoeffField d) with hf
  have hagree : ∀ (i j : Option ℕ) (b : Source.Coarse.Carrier d)
      (hbi : b ∈ cover i) (hbj : b ∈ cover j), f i ⟨b, hbi⟩ = f j ⟨b, hbj⟩ := by
    intro i j b hbi hbj
    cases i with
    | none =>
        cases j with
        | none => rfl
        | some k => exact absurd (Set.mem_iUnion.mpr ⟨k, hbj⟩) hbi
    | some k =>
        cases j with
        | none => exact absurd (Set.mem_iUnion.mpr ⟨k, hbi⟩) hbj
        | some _ => rfl
  have hcover : ⋃ i : Option ℕ, cover i = Set.univ := by
    ext b
    refine ⟨fun _ => Set.mem_univ b, fun _ => ?_⟩
    by_cases hb : b ∈ covered
    · rcases Set.mem_iUnion.mp hb with ⟨k, hk⟩
      exact Set.mem_iUnion.mpr ⟨some k, by simpa [hcoverdef] using hk⟩
    · exact Set.mem_iUnion.mpr ⟨none, by simpa [hcoverdef] using hb⟩
  have hcover_meas : ∀ i : Option ℕ, MeasurableSet (cover i) := by
    intro i
    have hk : ∀ k : ℕ, MeasurableSet (slice k) := fun k =>
      measurableSet_sourceLocal_aeeSlice hUopen k
    cases i with
    | none => exact (MeasurableSet.iUnion hk).compl
    | some k => exact hk k
  have hfm : ∀ i : Option ℕ, Measurable (f i) := by
    intro i
    cases i with
    | none => exact measurable_const
    | some k =>
        have hEntry : ∀ (i' j' : Fin d) {φ : Vec d → ℝ}, ContDiff ℝ (⊤ : ℕ∞) φ →
            HasCompactSupport φ → tsupport φ ⊆ U →
            Measurable fun x : cover (some k) =>
              entryTestR i' j' φ (Source.Coarse.coarseToRegular (x : Source.Coarse.Carrier d)) := by
          intro i' j' φ hcont hcpt hsupp
          have hentry : @Measurable (RegCoeffField d) ℝ (SmoothLocalSigmaR U) _
              (entryTestR i' j' φ) := by
            intro t ht
            exact MeasurableSpace.measurableSet_generateFrom
              ⟨i', j', φ, hcont, hcpt, hsupp, t, ht, rfl⟩
          exact hentry.comp
            ((Source.Coarse.measurable_coarseToRegular_smoothLocal U
              hUopen.measurableSet).comp measurable_subtype_coe)
        exact measurable_Mu_of_measurable_entryTest hUopen hUfin hvol
          (A := fun x : cover (some k) =>
            Source.Coarse.coarseToRegular (x : Source.Coarse.Carrier d))
          (fun x => x.2) hEntry P0
  have hY_eq : (fun b : Source.Coarse.Carrier d => Mu U P0 (b.1 : CoeffField d))
      = Set.liftCover cover f hagree hcover := by
    funext b
    obtain ⟨k, hbk⟩ := exists_source_aeeQuantitativeEllipticSlice hUopen.measurableSet hUbdd b
    have hb_cover : b ∈ cover (some k) := hbk
    rw [Set.liftCover_of_mem (S := cover) (f := f) (hf := hagree) (hS := hcover)
      (i := some k) hb_cover]
  rw [hY_eq]
  exact measurable_liftCover cover hcover_meas f hfm hagree hcover

/-- The coarse-grained energy of a bounded open cell of positive volume is
measurable on the exact coarse source for its global sigma-field. -/
theorem measurable_Mu_carrier {U : Set (Vec d)} (hUopen : IsOpen U)
    (hUbdd : IsBoundedDomain U) (hvol : 0 < (volume U).toReal) (P0 : BlockVec d) :
    Measurable fun b : Source.Coarse.Carrier d => Mu U P0 (b.1 : CoeffField d) :=
  Measurable.mono (measurable_Mu_carrier_local hUopen hUbdd hvol P0)
    (Source.Coarse.localSigma_mono hUopen.measurableSet MeasurableSet.univ
      (Set.subset_univ _)) le_rfl

/-! ## The measurability clause on the coefficient space -/

/-- **The coarse-grained energy of a bounded open cell of positive volume is
measurable on the coefficient space.**  The representative map into the exact
coarse source is measurable for the global sigma-fields and leaves the energy
unchanged. -/
theorem measurable_Mu_coeffSpace {U : Set (Vec d)} (hUopen : IsOpen U)
    (hUbdd : IsBoundedDomain U) (hvol : 0 < (volume U).toReal) (P0 : BlockVec d) :
    Measurable fun a : CoeffSpace d => Mu U P0 (⇑a.1 : CoeffField d) := by
  have hEq : (fun a : CoeffSpace d => Mu U P0 (⇑a.1 : CoeffField d))
      = (fun b : Source.Coarse.Carrier d => Mu U P0 (b.1 : CoeffField d)) ∘
        sourceRepresentative := by
    funext a
    exact Mu_congr_of_ae_eq (ae_restrict_of_ae (sourceRepresentative_ae_eq a)) P0
  rw [hEq]
  exact (measurable_Mu_carrier hUopen hUbdd hvol P0).comp measurable_sourceRepresentative

/-- **The measurability of the variational coarse block, on every bounded
open cell of positive volume and for every law at once.** -/
theorem hasMeasurableCoarseBlock_of_isBoundedDomain (P : Measure (CoeffSpace d))
    {U : Set (Vec d)} (hUopen : IsOpen U) (hUbdd : IsBoundedDomain U)
    (hvol : 0 < (volume U).toReal) : HasMeasurableCoarseBlock P U :=
  hasMeasurableCoarseBlock_of_measurable_Mu P
    fun Q => measurable_Mu_coeffSpace hUopen hUbdd hvol Q

/-! ## The clause on the adapted cells -/

/-- **The coarse response on an adapted cell is measurable in the coefficient
field**, for every law at once. -/
theorem hasMeasurableCoarseBlock_adaptedCell (P : Measure (CoeffSpace d)) {q : Mat d}
    (hq : q.PosDef) (j : ℤ) : HasMeasurableCoarseBlock P (adaptedCell q j) :=
  hasMeasurableCoarseBlock_of_isBoundedDomain P
    (isOpenBoundedConvexDomain_adaptedCell hq j).isOpen
    (isOpenBoundedConvexDomain_adaptedCell hq j).isBoundedDomain
    (toReal_volume_adaptedCell_pos hq j)

/-- **The coarse response on an aligned adapted cell is measurable in the
coefficient field**, for every law at once. -/
theorem hasMeasurableCoarseBlock_adaptedCellAt (P : Measure (CoeffSpace d)) {q : Mat d}
    (hq : q.PosDef) (j : ℤ) (w : Fin d → ℤ) :
    HasMeasurableCoarseBlock P (adaptedCellAt q j w) := by
  refine hasMeasurableCoarseBlock_of_isBoundedDomain P
    (isOpenBoundedConvexDomain_adaptedCellAt hq j w).isOpen
    (isOpenBoundedConvexDomain_adaptedCellAt hq j w).isBoundedDomain ?_
  have hpos : 0 < volume (adaptedCellAt q j w) := volume_adaptedCellAt_pos hq j w
  have hfin : volume (adaptedCellAt q j w) ≠ ⊤ :=
    ne_of_lt (isOpenBoundedConvexDomain_adaptedCellAt hq j w).volume_lt_top
  exact ENNReal.toReal_pos hpos.ne' hfin

/-- The measurability clause at a rounded adapted grid: the grid's positivity is
part of `IsRoundedGrid`. -/
theorem hasMeasurableCoarseBlock_adaptedCell_of_isRoundedGrid (P : Measure (CoeffSpace d))
    {l : ℤ} {q : Mat d} (hq : IsRoundedGrid l q) (j : ℤ) :
    HasMeasurableCoarseBlock P (adaptedCell q j) :=
  hasMeasurableCoarseBlock_adaptedCell P (posDef_of_isRoundedGrid hq) j

end

end Recurrence
end HighContrast
end Homogenization
