/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Annealed.Measurability
import Homogenization.Probability.RegCoeffField.SliceMeasurability
import Homogenization.Probability.RegCoeffField.SmoothSigma
import Homogenization.Probability.Source.Coarse.RegIntegralAdapter
import Mathlib.Geometry.Manifold.PartitionOfUnity
import Mathlib.MeasureTheory.Constructions.BorelSpace.Metrizable
import Mathlib.MeasureTheory.Integral.DominatedConvergence
import Mathlib.Topology.MetricSpace.HausdorffDistance

/-!
# Ellipticity slices of a general cell are smooth-test measurable

The countable presentation of the coarse-grained energy needs the coefficient
field to be confined to one quantitative ellipticity slice of the cell, and the
gluing over slices needs the slice events themselves to be measurable for the
sigma-field the coefficient space actually carries — the one generated by the
smooth linear statistics of the field.

That is proved here for an arbitrary open cell.  The a.e. ellipticity event on
an open set is a countable intersection of ellipticity conditions on averages
over rational balls inside it, and the average over a compact ball is a limit of
smooth entry tests: a sequence of smooth cutoffs supported in the cell and
increasing to the ball indicator gives the convergence by dominated
convergence, the dominating function being the entry itself on a compact
neighbourhood of the ball, which is integrable because the field is locally
integrable.
-/

namespace Homogenization
namespace HighContrast
namespace Recurrence

open MeasureTheory Metric Filter Topology

open scoped Manifold

noncomputable section

variable {d : ℕ}

/-! ## Smooth cutoffs approximating a compact ball inside an open cell -/

/-- A compact set inside an open set is the pointwise limit of smooth cutoffs
supported in the open set, all of them supported in one compact neighbourhood
and taking values in `[0,1]`. -/
theorem exists_smooth_cutoff_seq {U B : Set (Vec d)} (hUopen : IsOpen U)
    (hBcpt : IsCompact B) (hBU : B ⊆ U) :
    ∃ K : Set (Vec d), ∃ psi : ℕ → Vec d → ℝ,
      IsCompact K ∧ K ⊆ U ∧
      (∀ n, ContDiff ℝ (⊤ : ℕ∞) (psi n) ∧ HasCompactSupport (psi n) ∧
        tsupport (psi n) ⊆ U ∧ Function.support (psi n) ⊆ K ∧
          ∀ x, psi n x ∈ Set.Icc 0 1) ∧
      ∀ x, Tendsto (fun n => psi n x) atTop
        (𝓝 (Set.indicator B (fun _ => (1 : ℝ)) x)) := by
  classical
  obtain ⟨eps, hepspos, hepsU⟩ := hBcpt.exists_cthickening_subset_open hUopen hBU
  set delta : ℕ → ℝ := fun n => eps / (n + 1) with hdelta
  have hdeltapos : ∀ n, 0 < delta n := fun n => by
    rw [hdelta]
    positivity
  have hdeltale : ∀ n, delta n ≤ eps := fun n => by
    have hn : 1 ≤ (n : ℝ) + 1 := by
      have hn0 : (0 : ℝ) ≤ (n : ℝ) := by positivity
      linarith only [hn0]
    rw [hdelta]
    calc eps / ((n : ℝ) + 1) ≤ eps / 1 :=
          div_le_div_of_nonneg_left hepspos.le (by positivity) hn
      _ = eps := by rw [div_one]
  have hBint : ∀ n, B ⊆ interior (cthickening (delta n) B) := fun n =>
    (self_subset_thickening (hdeltapos n) B).trans
      (thickening_subset_interior_cthickening (delta n) B)
  choose psi hpsione hpsizero hpsirange using fun n =>
    exists_contMDiffMap_one_nhds_of_subset_interior (I := 𝓘(ℝ, Vec d)) (n := (⊤ : ℕ∞))
      hBcpt.isClosed (hBint n)
  refine ⟨cthickening eps B, fun n => psi n, hBcpt.cthickening, hepsU, ?_, ?_⟩
  · intro n
    have hsupp : Function.support (fun x => psi n x) ⊆ cthickening (delta n) B := by
      intro x hx
      by_contra hxT
      exact hx (hpsizero n x hxT)
    have hcompact : HasCompactSupport (fun x => psi n x) :=
      HasCompactSupport.of_support_subset_isCompact hBcpt.cthickening hsupp
    have htsupp : tsupport (fun x => psi n x) ⊆ U := by
      have htsuppT : tsupport (fun x => psi n x) ⊆ cthickening (delta n) B := by
        simpa [tsupport] using closure_minimal hsupp isClosed_cthickening
      exact htsuppT.trans ((cthickening_mono (hdeltale n) B).trans hepsU)
    exact ⟨(psi n).contMDiff.contDiff, hcompact, htsupp,
      hsupp.trans (cthickening_mono (hdeltale n) B), hpsirange n⟩
  · intro x
    by_cases hx : x ∈ B
    · rw [show Set.indicator B (fun _ => (1 : ℝ)) x = 1 by simp [hx]]
      have hone : ∀ n, psi n x = 1 := fun n => (hpsione n).self_of_nhdsSet x hx
      simp_rw [hone]
      exact tendsto_const_nhds
    · have hxcl : x ∉ closure B := by simpa [hBcpt.isClosed.closure_eq] using hx
      obtain ⟨rho, ⟨hrhopos, hrholt⟩⟩ :=
        Metric.exists_real_pos_lt_infEDist_of_notMem_closure hxcl
      have hdeltatend : Tendsto delta atTop (𝓝 0) := by
        simpa only [hdelta, div_eq_mul_inv, one_mul, mul_zero] using
          (tendsto_const_nhds.mul tendsto_one_div_add_atTop_nhds_zero_nat :
            Tendsto (fun n : ℕ => eps * (1 / ((n : ℝ) + 1))) atTop (𝓝 (eps * 0)))
      have hsmall : ∀ᶠ n in atTop, delta n < rho := by
        rw [Metric.tendsto_nhds] at hdeltatend
        specialize hdeltatend rho hrhopos
        filter_upwards [hdeltatend] with n hn
        simpa only [dist_zero_right, Real.norm_eq_abs,
          abs_of_nonneg (hdeltapos n).le] using hn
      rw [show Set.indicator B (fun _ => (1 : ℝ)) x = 0 by simp [hx]]
      rcases (eventually_atTop.1 hsmall) with ⟨N, hN⟩
      refine tendsto_atTop_of_eventually_const (i₀ := N) fun n hn => ?_
      refine hpsizero n x fun hxt => ?_
      rw [mem_cthickening_iff] at hxt
      have hdeltarho : ENNReal.ofReal (delta n) < ENNReal.ofReal rho :=
        (ENNReal.ofReal_lt_ofReal_iff hrhopos).mpr (hN n hn)
      exact (not_le_of_gt (hdeltarho.trans hrholt)) hxt

/-! ## Ball averages are smooth-test measurable -/

/-- The entry test against a smooth cutoff sequence converges to the entry test
against the ball indicator, uniformly in the field. -/
theorem exists_smooth_entryTestR_approximation {U B : Set (Vec d)} (hUopen : IsOpen U)
    (hBcpt : IsCompact B) (hBU : B ⊆ U) :
    ∃ psi : ℕ → Vec d → ℝ,
      (∀ n, ContDiff ℝ (⊤ : ℕ∞) (psi n) ∧ HasCompactSupport (psi n) ∧
        tsupport (psi n) ⊆ U) ∧
      ∀ (i j : Fin d) (a : RegCoeffField d),
        Tendsto (fun n => entryTestR i j (psi n) a) atTop
          (𝓝 (entryTestR i j (Set.indicator B (fun _ => (1 : ℝ))) a)) := by
  obtain ⟨K, psi, hKcpt, -, hpsi, hlim⟩ := exists_smooth_cutoff_seq hUopen hBcpt hBU
  refine ⟨psi, fun n => ⟨(hpsi n).1, (hpsi n).2.1, (hpsi n).2.2.1⟩, ?_⟩
  intro i j a
  have hbound_integrable : Integrable (K.indicator fun x => |a.toFun x i j|) volume := by
    rw [integrable_indicator_iff hKcpt.measurableSet]
    simpa only [Real.norm_eq_abs] using!
      ((a.entry_locInt i j).integrableOn_isCompact hKcpt).norm
  have hF_measurable : ∀ n, AEStronglyMeasurable (fun x => a.toFun x i j * psi n x) volume :=
    fun n => ((a.entry_measurable i j).mul (hpsi n).1.continuous.measurable).aestronglyMeasurable
  have hF_bound : ∀ n, ∀ᵐ x ∂volume,
      ‖a.toFun x i j * psi n x‖ ≤ K.indicator (fun x => |a.toFun x i j|) x := by
    intro n
    filter_upwards with x
    by_cases hxK : x ∈ K
    · rw [Set.indicator_of_mem hxK, norm_mul, Real.norm_eq_abs]
      have hpsi01 := (hpsi n).2.2.2.2 x
      rw [Real.norm_eq_abs, abs_of_nonneg hpsi01.1]
      exact mul_le_of_le_one_right (abs_nonneg _) hpsi01.2
    · have hzero : psi n x = 0 := by
        have hxSupp : x ∉ Function.support (psi n) := fun hx => hxK ((hpsi n).2.2.2.1 hx)
        simpa only [Function.mem_support, not_not] using hxSupp
      rw [Set.indicator_of_notMem hxK, hzero, mul_zero, norm_zero]
  have hF_lim : ∀ᵐ x ∂volume,
      Tendsto (fun n => a.toFun x i j * psi n x) atTop
        (𝓝 (a.toFun x i j * Set.indicator B (fun _ => (1 : ℝ)) x)) :=
    Filter.Eventually.of_forall fun x => tendsto_const_nhds.mul (hlim x)
  simpa only [entryTestR] using
    tendsto_integral_of_dominated_convergence (K.indicator fun x => |a.toFun x i j|)
      hF_measurable hbound_integrable hF_bound hF_lim

/-- The average of a field over a compact ball inside an open cell is measurable
for the smooth entry-test sigma-field of the cell. -/
theorem measurable_avgMat_smoothLocalSigmaR {U B : Set (Vec d)} (hUopen : IsOpen U)
    (hBcpt : IsCompact B) (hBU : B ⊆ U) :
    @Measurable (RegCoeffField d) (Mat d) (SmoothLocalSigmaR U) _ (avgMat B) := by
  let : MeasurableSpace (RegCoeffField d) := SmoothLocalSigmaR U
  obtain ⟨psi, hpsi, hlim⟩ := exists_smooth_entryTestR_approximation hUopen hBcpt hBU
  refine @measurable_matrix_of_entries d (RegCoeffField d) (SmoothLocalSigmaR U) (avgMat B) ?_
  intro i j
  have hmeas : ∀ n, @Measurable (RegCoeffField d) ℝ (SmoothLocalSigmaR U) _
      (entryTestR i j (psi n)) := by
    intro n t ht
    exact MeasurableSpace.measurableSet_generateFrom
      ⟨i, j, psi n, (hpsi n).1, (hpsi n).2.1, (hpsi n).2.2, t, ht, rfl⟩
  have htend : Tendsto (fun n => entryTestR i j (psi n)) atTop
      (𝓝 (entryTestR i j (Set.indicator B (fun _ => (1 : ℝ))))) := by
    rw [tendsto_pi_nhds]
    intro a
    exact hlim i j a
  have hindicator : @Measurable (RegCoeffField d) ℝ (SmoothLocalSigmaR U) _
      (entryTestR i j (Set.indicator B (fun _ => (1 : ℝ)))) :=
    measurable_of_tendsto_metrizable hmeas htend
  have heq : (fun a : RegCoeffField d => avgMat B a i j)
      = fun a => (volume B).toReal⁻¹ • entryTestR i j (Set.indicator B (fun _ => (1 : ℝ))) a := by
    funext a
    exact avgMat_entry_eq_smul_entryTestR i j B hBcpt.measurableSet a
  rw [heq]
  exact hindicator.const_smul ((volume B).toReal⁻¹)

/-! ## The slice event is smooth-test measurable -/

/-- The rational-ball presentation of the a.e. ellipticity event is measurable
for the smooth entry-test sigma-field of an open cell. -/
theorem measurableSet_slicePart_smoothLocalSigmaR {U : Set (Vec d)} (hUopen : IsOpen U)
    (lam Lam : ℝ) : MeasurableSet[SmoothLocalSigmaR U] (slicePart U lam Lam) := by
  refine MeasurableSet.iInter fun q => MeasurableSet.iInter fun r =>
    MeasurableSet.iInter fun _hpos => MeasurableSet.iInter fun hsub => ?_
  have hBcpt : IsCompact (closedBall (ratPt q) (r : ℝ)) := isCompact_closedBall _ _
  have hpre :
      {a : RegCoeffField d | IsEllipticMatrix lam Lam (avgMat (closedBall (ratPt q) (r : ℝ)) a)}
        = avgMat (closedBall (ratPt q) (r : ℝ)) ⁻¹' {A : Mat d | IsEllipticMatrix lam Lam A} :=
    rfl
  rw [hpre]
  exact (measurable_avgMat_smoothLocalSigmaR hUopen hBcpt hsub) measurableSet_isEllipticMatrix

/-- **The quantitative ellipticity slice of an open cell is measurable for the
smooth entry-test sigma-field.**  This is CoarseGraining's cube statement with
the cube removed. -/
theorem measurableSet_smoothLocalSigmaR_aeeSlice {U : Set (Vec d)} (hUopen : IsOpen U)
    (k : ℕ) :
    MeasurableSet[SmoothLocalSigmaR U]
      {a : RegCoeffField d | AEEQuantitativeEllipticSlice U k a.toFun} := by
  have hEvent : {a : RegCoeffField d | AEEQuantitativeEllipticSlice U k a.toFun}
      = {a : RegCoeffField d |
          ∀ᵐ x ∂volume.restrict U,
            IsEllipticMatrix ((k + 1 : ℝ)⁻¹) (k + 1 : ℝ) (a.toFun x)} := by
    ext a
    simp only [Set.mem_ofPred_eq]
    exact aeeQuantitativeEllipticSlice_carrier_iff U hUopen.measurableSet k a
  rw [hEvent, setOf_aeRestrict_isEllipticMatrix_eq_slicePart hUopen]
  exact measurableSet_slicePart_smoothLocalSigmaR hUopen _ _

/-- **The quantitative ellipticity slice of an open cell is measurable on the
exact coarse source**, for the source's own local sigma-field. -/
theorem measurableSet_sourceLocal_aeeSlice {U : Set (Vec d)} (hUopen : IsOpen U)
    (k : ℕ) :
    @MeasurableSet (Source.Coarse.Carrier d)
      (Source.Coarse.localSigma U hUopen.measurableSet)
      {a : Source.Coarse.Carrier d | AEEQuantitativeEllipticSlice U k a.1} :=
  (measurableSet_smoothLocalSigmaR_aeeSlice hUopen k).preimage
    (Source.Coarse.measurable_coarseToRegular_smoothLocal U hUopen.measurableSet)

end

end Recurrence
end HighContrast
end Homogenization
