/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Provider.Recurrence.CellLocalMeasurability

/-!
# Joint independence of a unit-separated family of local sigma-fields

The unit-range assumption is a statement about *two* Borel sets at sup-distance
at least one.  The finite-range averaging lemma needs the joint independence of
a whole finite family, and derives it by the grouping argument printed there:
enumerate the family, observe that the union of the cells already treated stays
at sup-distance at least one from the next cell, that the sigma-field of that
union dominates the sigma-fields of its members, and induct.

Both ingredients are elementary here.  Sup-separation from a fixed set is
inherited by any union of separated sets, because the separation is a pointwise
condition.  And the sigma-field `F(U)` is generated by the linear statistics
with test support inside `U`, so it grows with `U`; the intersection of finitely
many sets, each measurable for the sigma-field of its own cell, is therefore
measurable for the sigma-field of the union.  No partition of unity is needed:
the printed proof uses one to obtain the *equality* of the sigma-field of the
union with the join, whereas the induction consumes only the inclusion of the
join in the sigma-field of the union.

The conclusions are stated for an arbitrary index type: joint independence of
the sigma-fields, and joint independence of any family of random variables each
measurable for the sigma-field of its own cell.  The last lemma records that
locally measurable random variables are measurable for the global structure,
which is what a moment inequality applied to them will ask for.
-/

namespace Homogenization
namespace HighContrast
namespace Recurrence

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-! ## Unit separation is closed under finite unions on one side -/

/-- **A set separated from each member of a finite family is separated from
their union.**  Sup-separation is a pointwise condition, so this is immediate. -/
theorem unitSeparated_biUnion_right {ι : Type*} {U : Set (Vec d)}
    {V : ι → Set (Vec d)} {s : Finset ι} (h : ∀ i ∈ s, UnitSeparated U (V i)) :
    UnitSeparated U (⋃ i ∈ s, V i) := by
  intro x y hx hy
  simp only [Set.mem_iUnion] at hy
  obtain ⟨i, hi, hyi⟩ := hy
  exact h i hi hx hyi

/-! ## The sigma-field of a union dominates the join -/

/-- **The intersection of finitely many locally measurable sets is measurable
for the sigma-field of the union of the cells.**  This is the inclusion of the
join `⋁ F(U_i)` in `F(⋃ U_i)`, the only half of the printed identity that the
grouping induction uses. -/
private theorem measurableSet_biInter_coeffSigma_biUnion {ι : Type*}
    {U : ι → Set (Vec d)} {f : ι → Set (CoeffSpace d)} {s : Finset ι}
    (hf : ∀ i ∈ s, @MeasurableSet (CoeffSpace d) (coeffSigma d (U i)) (f i)) :
    @MeasurableSet (CoeffSpace d) (coeffSigma d (⋃ i ∈ s, U i)) (⋂ i ∈ s, f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
      have hsubset_i : U i ⊆ ⋃ j ∈ insert i s, U j := by
        intro x hx
        simp only [Set.mem_iUnion, Finset.mem_insert]
        exact ⟨i, Or.inl rfl, hx⟩
      have hsubset_s : (⋃ j ∈ s, U j) ⊆ ⋃ j ∈ insert i s, U j := by
        intro x hx
        simp only [Set.mem_iUnion, Finset.mem_insert] at hx ⊢
        obtain ⟨j, hj, hxj⟩ := hx
        exact ⟨j, Or.inr hj, hxj⟩
      have hi_meas : @MeasurableSet (CoeffSpace d)
          (coeffSigma d (⋃ j ∈ insert i s, U j)) (f i) :=
        coeffSigma_mono hsubset_i (f i) (hf i (by simp))
      have hs_meas : @MeasurableSet (CoeffSpace d)
          (coeffSigma d (⋃ j ∈ insert i s, U j)) (⋂ j ∈ s, f j) :=
        coeffSigma_mono hsubset_s (⋂ j ∈ s, f j)
          (ih fun j hj => hf j (by simp [hj]))
      simpa [Finset.set_biInter_insert, hi] using hi_meas.inter hs_meas

/-! ## Joint independence -/

/-- **A pairwise unit-separated family of local sigma-fields is jointly
independent.**  This is the grouping induction of
`l.fixed.geometry.matrix.averaging`, carried out in the dialect of unit range of
dependence: at each step the unit-range assumption separates the next
cell from the union of those already taken. -/
theorem iIndep_coeffSigma_of_pairwise_unitSeparated {ι : Type*}
    (P : Measure (CoeffSpace d)) [IsProbabilityMeasure P]
    (hP : HCPoly.Frozen.IsUnitRangeLaw P) {U : ι → Set (Vec d)}
    (hU : ∀ i, MeasurableSet (U i))
    (hsep : Pairwise fun i j => UnitSeparated (U i) (U j)) :
    ProbabilityTheory.iIndep (fun i => coeffSigma d (U i)) P := by
  classical
  rw [ProbabilityTheory.iIndep_iff]
  intro s f hf
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
      have hUnion : MeasurableSet (⋃ j ∈ s, U j) :=
        Finset.measurableSet_biUnion _ fun j _ => hU j
      have hsep_union : UnitSeparated (U i) (⋃ j ∈ s, U j) :=
        unitSeparated_biUnion_right (U := U i) (V := U) fun j hj =>
          hsep fun hij => hi (hij ▸ hj)
      have hs_meas : @MeasurableSet (CoeffSpace d)
          (coeffSigma d (⋃ j ∈ s, U j)) (⋂ j ∈ s, f j) :=
        measurableSet_biInter_coeffSigma_biUnion (U := U) (f := f) (s := s)
          fun j hj => hf j (by simp [hj])
      have h_inter : P (f i ∩ ⋂ j ∈ s, f j) = P (f i) * P (⋂ j ∈ s, f j) :=
        (ProbabilityTheory.Indep_iff (coeffSigma d (U i))
              (coeffSigma d (⋃ j ∈ s, U j)) P).1
          (hP (U i) (⋃ j ∈ s, U j) (hU i) hUnion hsep_union)
          (f i) (⋂ j ∈ s, f j) (hf i (by simp)) hs_meas
      calc
        P (⋂ j ∈ insert i s, f j) = P (f i ∩ ⋂ j ∈ s, f j) := by simp
        _ = P (f i) * P (⋂ j ∈ s, f j) := h_inter
        _ = P (f i) * ∏ j ∈ s, P (f j) := by rw [ih fun j hj => hf j (by simp [hj])]
        _ = ∏ j ∈ insert i s, P (f j) := by simp [Finset.prod_insert, hi]

/-- **A family of locally measurable random variables over pairwise
unit-separated cells is jointly independent.**  This is the form the moment
inequalities of the finite-range averaging lemma consume. -/
theorem iIndepFun_of_measurable_coeffSigma {ι : Type*}
    (P : Measure (CoeffSpace d)) [IsProbabilityMeasure P]
    (hP : HCPoly.Frozen.IsUnitRangeLaw P) {U : ι → Set (Vec d)}
    (hU : ∀ i, MeasurableSet (U i)) {β : ι → Type*} [∀ i, MeasurableSpace (β i)]
    {X : ∀ i, CoeffSpace d → β i}
    (hX : ∀ i, @Measurable (CoeffSpace d) (β i) (coeffSigma d (U i)) _ (X i))
    (hsep : Pairwise fun i j => UnitSeparated (U i) (U j)) :
    ProbabilityTheory.iIndepFun X P := by
  classical
  rw [ProbabilityTheory.iIndepFun_iff_iIndep, ProbabilityTheory.iIndep_iff]
  intro s f hf
  exact (ProbabilityTheory.iIndep_iff (fun i => coeffSigma d (U i)) P).1
    (iIndep_coeffSigma_of_pairwise_unitSeparated P hP hU hsep) s
    fun i hi => (hX i).comap_le (f i) (hf i hi)

/-- A random variable measurable for the sigma-field of a cell is measurable for
the global structure of the coefficient space. -/
theorem measurable_of_measurable_coeffSigma {U : Set (Vec d)} {β : Type*}
    [MeasurableSpace β] {X : CoeffSpace d → β}
    (hX : @Measurable (CoeffSpace d) β (coeffSigma d U) _ X) : Measurable X :=
  hX.mono (coeffSigma_mono (Set.subset_univ U)) le_rfl

end

end Recurrence
end HighContrast
end Homogenization
