/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Setup.CoefficientSpace
import Mathlib.Probability.Independence.Basic

/-!
# The local sigma-fields of the coefficient space

The sigma-fields `F(U)` of the coefficient-law setup in `s.introduction` are
generated by the smooth linear statistics of the coefficient field with test
support inside `U`.  This file fixes those generators, the canonical global
measurable structure, the unit separation relation used by the unit range of
dependence, and the two facts the
sigma-fields must have to be non-degenerate: the generating integrals converge,
and the integer translation action is measurable.
-/

namespace Homogenization
namespace HighContrast

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-- A test function for the local sigma-field `F(U)`: smooth, compactly
supported, with support contained in `U` (the paper's `C_c^∞(U)`). -/
structure IsLocalTest (U : Set (Vec d)) (φ : Vec d → ℝ) : Prop where
  contDiff : ContDiff ℝ (⊤ : ℕ∞) φ
  hasCompactSupport : HasCompactSupport φ
  tsupport_subset : tsupport φ ⊆ U

/-- The generating linear statistics of `F(U)`:
`a ↦ ∫ e' · a(x) e φ(x) dx` over `ℝ^d`. -/
def coeffPairing (e e' : Vec d) (φ : Vec d → ℝ) (a : CoeffSpace d) : ℝ :=
  ∫ x, vecDot e' (matVecMul (a.1 x) e) * φ x ∂volume

/-- The local sigma-field `F(U)` generated by the smooth linear statistics with
test support inside `U`. -/
@[instance_reducible]
def coeffSigma (d : ℕ) (U : Set (Vec d)) : MeasurableSpace (CoeffSpace d) :=
  MeasurableSpace.generateFrom
    {s | ∃ (e e' : Vec d) (φ : Vec d → ℝ), IsLocalTest U φ ∧
      ∃ t : Set ℝ, MeasurableSet t ∧ s = coeffPairing e e' φ ⁻¹' t}

/-- The global sigma-field `F = F(ℝ^d)` is the canonical measurable structure
of the coefficient space. -/
instance instMeasurableSpaceCoeffSpace (d : ℕ) : MeasurableSpace (CoeffSpace d) :=
  coeffSigma d Set.univ

/-- `dist_∞(U, V) ≥ 1`, in the pointwise form. -/
def UnitSeparated (U V : Set (Vec d)) : Prop :=
  ∀ ⦃x y : Vec d⦄, x ∈ U → y ∈ V → 1 ≤ Source.AKL.supDist x y

/-! ## The generating statistics converge -/

/-- The generating linear statistics have an integrable integrand: the test
function is continuous, vanishes outside a compact set, and the coefficient
entries are essentially bounded on any ball containing that set. -/
theorem integrable_coeffPairing_integrand (e e' : Vec d) {U : Set (Vec d)}
    {φ : Vec d → ℝ} (hφ : IsLocalTest U φ) (a : CoeffSpace d) :
    Integrable (fun x => vecDot e' (matVecMul (a.1 x) e) * φ x) volume := by
  classical
  obtain ⟨R, hR, hKR⟩ :=
    exists_ball_of_isBounded hφ.hasCompactSupport.isCompact.isBounded
  obtain ⟨M, hM0, hM⟩ :=
    ae_abs_entry_le_of_aeUniformlyEllipticField a.2
      (Metric.isBounded_ball (x := (0 : Vec d)) (r := R))
  have hφint : Integrable φ volume :=
    (hφ.contDiff.continuous).integrable_of_hasCompactSupport hφ.hasCompactSupport
  have hcont : Continuous fun A : Mat d => vecDot e' (matVecMul A e) := by
    simp only [vecDot, matVecMul]
    exact continuous_finsetSum _ fun i _ => continuous_const.mul
      (continuous_finsetSum _ fun j _ =>
        (continuous_id.matrix_elem i j).mul continuous_const)
  have hmeas : AEStronglyMeasurable
      (fun x => vecDot e' (matVecMul ((a.1 : Vec d → Mat d) x) e)) volume :=
    hcont.comp_aestronglyMeasurable a.1.aestronglyMeasurable
  set C : ℝ := ∑ i : Fin d, |e' i| * ∑ j : Fin d, M * |e j| with hC
  have hC0 : 0 ≤ C := by
    rw [hC]
    positivity
  have hfun : (fun x => Set.indicator (Metric.ball (0 : Vec d) R)
        (fun y => vecDot e' (matVecMul ((a.1 : Vec d → Mat d) y) e)) x * φ x) =
      fun x => vecDot e' (matVecMul (a.1 x) e) * φ x := by
    funext x
    by_cases hxb : x ∈ Metric.ball (0 : Vec d) R
    · rw [Set.indicator_of_mem hxb]
    · rw [Set.indicator_of_notMem hxb, zero_mul,
        image_eq_zero_of_notMem_tsupport (fun hx => hxb (hKR hx)), mul_zero]
  rw [← hfun]
  refine Integrable.bdd_mul (c := C) hφint
    (hmeas.indicator measurableSet_ball) ?_
  filter_upwards [hM] with x hx
  by_cases hxb : x ∈ Metric.ball (0 : Vec d) R
  · rw [Set.indicator_of_mem hxb, Real.norm_eq_abs, hC]
    refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum fun i _ => ?_)
    rw [abs_mul]
    refine mul_le_mul_of_nonneg_left ?_ (abs_nonneg _)
    refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum fun j _ => ?_)
    rw [abs_mul]
    exact mul_le_mul_of_nonneg_right (hx hxb i j) (abs_nonneg _)
  · rw [Set.indicator_of_notMem hxb, norm_zero]
    exact hC0

/-! ## Measurability of the translation action -/

/-- The pairing of a translated field against a test function is the pairing of
the field against the translated test function. -/
theorem coeffPairing_translateCoeff (z : Fin d → ℤ) (e e' : Vec d)
    (φ : Vec d → ℝ) (a : CoeffSpace d) :
    coeffPairing e e' φ (translateCoeff z a) =
      coeffPairing e e' (fun y => φ (y - Source.AKL.intTranslation z)) a := by
  have hcomp :=
    (measurePreserving_add_right (volume : Measure (Vec d))
        (Source.AKL.intTranslation z)).integral_comp
      (Homeomorph.addRight (Source.AKL.intTranslation z)).measurableEmbedding
      (fun y => vecDot e' (matVecMul (a.1 y) e) *
        φ (y - Source.AKL.intTranslation z))
  rw [coeffPairing, coeffPairing, ← hcomp]
  refine integral_congr_ae ?_
  filter_upwards [Source.AKL.translateField_ae z a.1] with x hx
  rw [show ((translateCoeff z a).1 : Vec d → Mat d) x =
      Source.AKL.translateField z a.1 x from rfl, hx]
  congr 2
  abel

/-- The integer translation action is measurable for the global sigma-field.
Without it, stationarity of the coefficient law would be unsatisfiable and every
theorem carrying it vacuous. -/
theorem measurable_translateCoeff (z : Fin d → ℤ) :
    Measurable (translateCoeff (d := d) z) := by
  change @Measurable (CoeffSpace d) (CoeffSpace d) (coeffSigma d Set.univ)
    (MeasurableSpace.generateFrom
      {s | ∃ (e e' : Vec d) (φ : Vec d → ℝ), IsLocalTest Set.univ φ ∧
        ∃ t : Set ℝ, MeasurableSet t ∧ s = coeffPairing e e' φ ⁻¹' t})
    (translateCoeff z)
  apply measurable_generateFrom
  rintro s ⟨e, e', φ, hφ, t, ht, rfl⟩
  have hsub : ContDiff ℝ (⊤ : ℕ∞)
      (fun y : Vec d => y - Source.AKL.intTranslation z) :=
    contDiff_id.sub contDiff_const
  have hψ : IsLocalTest (Set.univ : Set (Vec d))
      (fun y => φ (y - Source.AKL.intTranslation z)) := by
    refine ⟨by simpa [Function.comp_def] using hφ.contDiff.comp hsub, ?_,
      Set.subset_univ _⟩
    simpa [Function.comp_def] using
      hφ.hasCompactSupport.comp_homeomorph
        (Homeomorph.subRight (Source.AKL.intTranslation z))
  have hset :
      translateCoeff (d := d) z ⁻¹' (coeffPairing e e' φ ⁻¹' t) =
        coeffPairing e e' (fun y => φ (y - Source.AKL.intTranslation z)) ⁻¹' t := by
    ext a
    change coeffPairing e e' φ (translateCoeff z a) ∈ t ↔ _
    rw [coeffPairing_translateCoeff]
    rfl
  rw [hset]
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨e, e', _, hψ, t, ht, rfl⟩

end

end HighContrast
end Homogenization
