/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import Audit.AlgebraicConvergence.SolutionBasic
import HCPoly.Frozen.CoarseEllipticityDagger
import HCPoly.Frozen.Stationarity
import HCPoly.Frozen.UnitRange

/-!
# Identification of the Mathlib-only vocabulary with the library objects

`Audit.AlgebraicConvergence.SolutionBasic` rebuilds, over Mathlib alone,
every object named by the statement of `t.algebraic.convergence`.  This file
identifies those rebuilt objects with the ones the library uses, so that
`Audit.AlgebraicConvergence.Solution` can prove the rebuilt statement from
`HCPoly.algebraic_convergence`.

Most of the vocabulary is definitionally shared: the coefficient space, its
integer translation action, the generating linear statistics, the triadic
geometry, the Schur parametrization, the intrinsic contrast, the aspect ratio,
the scalar dilation of a doubled block, the skew class, and the gauge conditions
all unfold to the same terms.  Three families of identification carry actual
content.

* **Structure copies.**  Doubled block matrices, doubled states, and the `H¹`
  and `H¹₀` witness records are inductive types, so the rebuilt copies are new
  types.  Each is converted by field shuffling, in both directions where the
  copy occurs in a hypothesis position.
* **The variational quantity.**  `Mu` is an infimum over admissible doubled
  states, whose admissibility quantifies over `H¹` and `H¹₀` witnesses in both
  polarities; the two infima are taken over the same set of reals.
* **The measurable structure.**  The local σ-fields are generated by the smooth
  linear statistics with test support in the given set.  The test class is a
  one-constructor record, so the two generating families are equal only
  propositionally; the resulting equality of σ-algebras is transported through
  the measures, the integrals, the almost-everywhere filters, and the
  independence relation.

The conclusions of `t.algebraic.convergence` produce a doubled block, so the
block-matrix conversion is used in the direction from the library to the rebuilt
copy as well: the Loewner order, the symmetry and positive definiteness
predicates, the scalar dilation and the Schur data all commute with it.
-/

namespace HCPoly
namespace StatementAudit
namespace AlgebraicConvergence
namespace Bridge

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-! ## Doubled block matrices -/

/-- The library block matrix of a rebuilt one. -/
def toRepoBlock (A : BlockMat d) : Homogenization.BlockMat d :=
  { upperLeft := A.upperLeft, upperRight := A.upperRight
    lowerLeft := A.lowerLeft, lowerRight := A.lowerRight }

/-- The rebuilt block matrix of a library one. -/
def ofRepoBlock (A : Homogenization.BlockMat d) : BlockMat d :=
  { upperLeft := A.upperLeft, upperRight := A.upperRight
    lowerLeft := A.lowerLeft, lowerRight := A.lowerRight }

theorem toRepoBlock_ofRepoBlock (A : Homogenization.BlockMat d) :
    toRepoBlock (ofRepoBlock A) = A := by
  cases A; rfl

theorem ofRepoBlock_toRepoBlock (A : BlockMat d) :
    ofRepoBlock (toRepoBlock A) = A := by
  cases A; rfl

theorem blockContrast_ofRepoBlock (A : Homogenization.BlockMat d) :
    blockContrast (ofRepoBlock A) = Homogenization.HighContrast.blockContrast A :=
  rfl

theorem aspectRatio_toRepoBlock (E : BlockMat d) :
    aspectRatio E = Homogenization.HighContrast.aspectRatio (toRepoBlock E) := by
  cases E; rfl

theorem toRepoBlock_blockScale (c : ℝ) (E : BlockMat d) :
    toRepoBlock (blockScale c E) =
      Homogenization.HighContrast.blockScale c (toRepoBlock E) := by
  cases E; rfl

theorem isSymmetricBlockMat_toRepoBlock {E : BlockMat d} (h : IsSymmetricBlockMat E) :
    Homogenization.IsSymmetricBlockMat (toRepoBlock E) := by
  cases E; exact h

theorem blockPosDef_toRepoBlock {E : BlockMat d} (h : BlockPosDef E) :
    Homogenization.Book.Ch02.BlockPosDef (toRepoBlock E) := by
  cases E; exact h

theorem blockMatLoewnerLE_toRepoBlock {A B : BlockMat d} (h : BlockMatLoewnerLE A B) :
    Homogenization.BlockMatLoewnerLE (toRepoBlock A) (toRepoBlock B) := by
  cases A; cases B; exact h

theorem ofRepoBlock_blockScale (c : ℝ) (A : Homogenization.BlockMat d) :
    ofRepoBlock (Homogenization.HighContrast.blockScale c A) =
      blockScale c (ofRepoBlock A) := by
  cases A; rfl

theorem isSymmetricBlockMat_ofRepoBlock {A : Homogenization.BlockMat d}
    (h : Homogenization.IsSymmetricBlockMat A) :
    IsSymmetricBlockMat (ofRepoBlock A) := by
  cases A; exact h

theorem blockPosDef_ofRepoBlock {A : Homogenization.BlockMat d}
    (h : Homogenization.Book.Ch02.BlockPosDef A) : BlockPosDef (ofRepoBlock A) := by
  cases A; exact h

theorem blockMatLoewnerLE_ofRepoBlock {A B : Homogenization.BlockMat d}
    (h : Homogenization.BlockMatLoewnerLE A B) :
    BlockMatLoewnerLE (ofRepoBlock A) (ofRepoBlock B) := by
  cases A; cases B; exact h

/-! ## The Schur data of a doubled block matrix -/

theorem schurSigmaStar_ofRepoBlock (A : Homogenization.BlockMat d) :
    schurSigmaStar (ofRepoBlock A) =
      Homogenization.HighContrast.schurSigmaStar A := by
  cases A; rfl

theorem schurSkew_ofRepoBlock (A : Homogenization.BlockMat d) :
    schurSkew (ofRepoBlock A) = Homogenization.HighContrast.schurSkew A := by
  cases A; rfl

theorem schurSigma_ofRepoBlock (A : Homogenization.BlockMat d) :
    schurSigma (ofRepoBlock A) = Homogenization.HighContrast.schurSigma A := by
  cases A; rfl

theorem isSkewMat_of_repo {h : Mat d} (hh : Homogenization.HighContrast.IsSkewMat h) :
    IsSkewMat h :=
  hh

/-! ## `H¹`, `H¹₀`, and doubled states -/

/-- The library `H¹` witness of a rebuilt one. -/
def toRepoH1 {U : Set (Vec d)} (u : H1Function U) : Homogenization.H1Function U :=
  { toFun := u.toFun, grad := u.grad, memL2 := u.memL2, gradMemL2 := u.gradMemL2
    hasWeakGradient := u.hasWeakGradient }

/-- The rebuilt `H¹` witness of a library one. -/
def ofRepoH1 {U : Set (Vec d)} (u : Homogenization.H1Function U) : H1Function U :=
  { toFun := u.toFun, grad := u.grad, memL2 := u.memL2, gradMemL2 := u.gradMemL2
    hasWeakGradient := u.hasWeakGradient }

/-- The library `H¹₀` witness of a rebuilt one. -/
def toRepoH10 {U : Set (Vec d)} (u : H10Function U) : Homogenization.H10Function U :=
  { toH1Function := toRepoH1 u.toH1Function
    approx := u.approx
    approx_smooth := u.approx_smooth
    approx_hasCompactSupport := u.approx_hasCompactSupport
    approx_support_subset := u.approx_support_subset
    tendsto_approx := u.tendsto_approx
    tendsto_approx_grad := u.tendsto_approx_grad }

/-- The rebuilt `H¹₀` witness of a library one. -/
def ofRepoH10 {U : Set (Vec d)} (u : Homogenization.H10Function U) : H10Function U :=
  { toH1Function := ofRepoH1 u.toH1Function
    approx := u.approx
    approx_smooth := u.approx_smooth
    approx_hasCompactSupport := u.approx_hasCompactSupport
    approx_support_subset := u.approx_support_subset
    tendsto_approx := u.tendsto_approx
    tendsto_approx_grad := u.tendsto_approx_grad }

/-- The library doubled state of a rebuilt one. -/
def toRepoState (X : BlockState d) : Homogenization.BlockState d :=
  { potential := X.potential, flux := X.flux }

/-- The rebuilt doubled state of a library one. -/
def ofRepoState (X : Homogenization.BlockState d) : BlockState d :=
  { potential := X.potential, flux := X.flux }

theorem isBlockMuAdmissible_toRepoState {U : Set (Vec d)} {Pv : BlockVec d}
    {X : BlockState d} (h : IsBlockMuAdmissible U Pv X) :
    Homogenization.IsBlockMuAdmissible U Pv (toRepoState X) :=
  ⟨h.1, ⟨toRepoH10 h.2.1.choose, h.2.1.choose_spec⟩, h.2.2.1,
    fun φ => h.2.2.2 (ofRepoH1 φ)⟩

theorem isBlockMuAdmissible_ofRepoState {U : Set (Vec d)} {Pv : BlockVec d}
    {X : Homogenization.BlockState d} (h : Homogenization.IsBlockMuAdmissible U Pv X) :
    IsBlockMuAdmissible U Pv (ofRepoState X) :=
  ⟨h.1, ⟨ofRepoH10 h.2.1.choose, h.2.1.choose_spec⟩, h.2.2.1,
    fun φ => h.2.2.2 (toRepoH1 φ)⟩

/-! ## The variational quantity and the coarse block response -/

theorem muValueSet_eq (U : Set (Vec d)) (Pv : BlockVec d) (a : CoeffField d) :
    muValueSet U Pv a = Homogenization.muValueSet U Pv a := by
  ext m
  constructor
  · rintro ⟨X, hX, hm⟩
    exact ⟨toRepoState X, isBlockMuAdmissible_toRepoState hX, hm⟩
  · rintro ⟨X, hX, hm⟩
    exact ⟨ofRepoState X, isBlockMuAdmissible_ofRepoState hX, hm⟩

theorem mu_eq (U : Set (Vec d)) (Pv : BlockVec d) (a : CoeffField d) :
    Mu U Pv a = Homogenization.Mu U Pv a := by
  rw [Mu, Homogenization.Mu, muValueSet_eq]

theorem coarseBlockEntry_eq (U : Set (Vec d)) (a : CoeffField d) (α β : BlockCoord d) :
    coarseBlockEntry U a α β =
      Homogenization.blockMatEntry (Homogenization.coarseBlockMatrix U a) α β := by
  rw [Homogenization.HighContrast.blockMatEntry_coarseBlockMatrix, coarseBlockEntry]
  by_cases h : α = β
  · rw [dif_pos h, if_pos h, mu_eq]
    rfl
  · rw [dif_neg h, if_neg h, mu_eq, mu_eq, mu_eq]
    rfl

theorem coarseBlockMatrix_eq (U : Set (Vec d)) (a : CoeffField d) :
    coarseBlockMatrix U a = ofRepoBlock (Homogenization.coarseBlockMatrix U a) := by
  have h := coarseBlockEntry_eq U a
  unfold coarseBlockMatrix ofRepoBlock
  congr 1
  · funext i j; exact h (Sum.inl i) (Sum.inl j)
  · funext i j; exact h (Sum.inl i) (Sum.inr j)
  · funext i j; exact h (Sum.inr i) (Sum.inl j)
  · funext i j; exact h (Sum.inr i) (Sum.inr j)

theorem coarseBlock_eq (U : Set (Vec d)) (a : CoeffSpace d) :
    coarseBlock U a = ofRepoBlock (Homogenization.HighContrast.coarseBlock U a) :=
  coarseBlockMatrix_eq U _

theorem toRepoBlock_coarseBlock (U : Set (Vec d)) (a : CoeffSpace d) :
    toRepoBlock (coarseBlock U a) = Homogenization.HighContrast.coarseBlock U a := by
  rw [coarseBlock_eq, toRepoBlock_ofRepoBlock]

/-! ## The local σ-fields -/

theorem isLocalTest_iff (U : Set (Vec d)) (φ : Vec d → ℝ) :
    IsLocalTest U φ ↔ Homogenization.HighContrast.IsLocalTest U φ :=
  ⟨fun h => ⟨h.contDiff, h.hasCompactSupport, h.tsupport_subset⟩,
    fun h => ⟨h.contDiff, h.hasCompactSupport, h.tsupport_subset⟩⟩

theorem coeffSigma_eq (d : ℕ) (U : Set (Vec d)) :
    coeffSigma d U = Homogenization.HighContrast.coeffSigma d U := by
  unfold coeffSigma Homogenization.HighContrast.coeffSigma
  congr 1
  ext s
  constructor
  · rintro ⟨e, e', φ, hφ, t, ht, rfl⟩
    exact ⟨e, e', φ, (isLocalTest_iff U φ).1 hφ, t, ht, rfl⟩
  · rintro ⟨e, e', φ, hφ, t, ht, rfl⟩
    exact ⟨e, e', φ, (isLocalTest_iff U φ).2 hφ, t, ht, rfl⟩

theorem instMeasurableSpace_eq (d : ℕ) :
    (instMeasurableSpaceCoeffSpace d) =
      Homogenization.HighContrast.instMeasurableSpaceCoeffSpace d :=
  coeffSigma_eq d Set.univ

/-! ## Transport along an equality of σ-algebras -/

/-- The same measure, read through an equality of σ-algebras on its carrier. -/
def castMeasure {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (μ : @Measure α m₁) : @Measure α m₂ :=
  h ▸ μ

theorem castMeasure_eq_iff {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (μ ν : @Measure α m₁) : castMeasure h μ = castMeasure h ν ↔ μ = ν := by
  subst h; exact Iff.rfl

theorem castMeasure_map {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (f : α → α) (μ : @Measure α m₁) :
    @Measure.map α α m₂ m₂ f (castMeasure h μ) =
      castMeasure h (@Measure.map α α m₁ m₁ f μ) := by
  subst h; rfl

theorem castMeasure_real {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (μ : @Measure α m₁) (s : Set α) : (castMeasure h μ).real s = μ.real s := by
  subst h; rfl

theorem castMeasure_integral {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (μ : @Measure α m₁) (f : α → ℝ) :
    ∫ a, f a ∂(castMeasure h μ) = ∫ a, f a ∂μ := by
  subst h; rfl

theorem castMeasure_ae {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (μ : @Measure α m₁) (p : α → Prop) :
    (∀ᵐ a ∂(castMeasure h μ), p a) ↔ ∀ᵐ a ∂μ, p a := by
  subst h; exact Iff.rfl

theorem isProbabilityMeasure_castMeasure {α : Type*} {m₁ m₂ : MeasurableSpace α}
    (h : m₁ = m₂) (μ : @Measure α m₁) (hμ : @IsProbabilityMeasure α m₁ μ) :
    @IsProbabilityMeasure α m₂ (castMeasure h μ) := by
  subst h; exact hμ

theorem indep_castMeasure {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    (s t : MeasurableSpace α) (μ : @Measure α m₁)
    (hst : @ProbabilityTheory.Indep α s t m₁ μ) :
    @ProbabilityTheory.Indep α s t m₂ (castMeasure h μ) := by
  subst h; exact hst

theorem measurable_castMeasure {α : Type*} {m₁ m₂ : MeasurableSpace α} (h : m₁ = m₂)
    {f : α → ℝ} (hf : @Measurable α ℝ m₁ _ f) : @Measurable α ℝ m₂ _ f := by
  subst h; exact hf

/-- The library law of a rebuilt one. -/
def toRepoLaw (P : Measure (CoeffSpace d)) :
    Measure (Homogenization.HighContrast.CoeffSpace d) :=
  castMeasure (instMeasurableSpace_eq d) P

/-! ## The annealed block and the annealed contrast -/

theorem coarseBlock_upperLeft_eq (U : Set (Vec d)) (a : CoeffSpace d) (i j : Fin d) :
    (coarseBlock U a).upperLeft i j =
      (Homogenization.HighContrast.coarseBlock U a).upperLeft i j := by
  rw [coarseBlock_eq]; rfl

theorem coarseBlock_upperRight_eq (U : Set (Vec d)) (a : CoeffSpace d) (i j : Fin d) :
    (coarseBlock U a).upperRight i j =
      (Homogenization.HighContrast.coarseBlock U a).upperRight i j := by
  rw [coarseBlock_eq]; rfl

theorem coarseBlock_lowerLeft_eq (U : Set (Vec d)) (a : CoeffSpace d) (i j : Fin d) :
    (coarseBlock U a).lowerLeft i j =
      (Homogenization.HighContrast.coarseBlock U a).lowerLeft i j := by
  rw [coarseBlock_eq]; rfl

theorem coarseBlock_lowerRight_eq (U : Set (Vec d)) (a : CoeffSpace d) (i j : Fin d) :
    (coarseBlock U a).lowerRight i j =
      (Homogenization.HighContrast.coarseBlock U a).lowerRight i j := by
  rw [coarseBlock_eq]; rfl

theorem annealedBlock_eq (P : Measure (CoeffSpace d)) (U : Set (Vec d)) :
    annealedBlock P U =
      ofRepoBlock (Homogenization.HighContrast.annealedBlock (toRepoLaw P) U) := by
  unfold annealedBlock Homogenization.HighContrast.annealedBlock ofRepoBlock toRepoLaw
  congr 1 <;> funext i j <;>
    simp only [Matrix.of_apply, castMeasure_integral, coarseBlock_upperLeft_eq,
      coarseBlock_upperRight_eq, coarseBlock_lowerLeft_eq, coarseBlock_lowerRight_eq] <;>
    rfl

/-- The centred cube of the rebuilt triadic geometry is the library one. -/
theorem centeredCube_eq (d : ℕ) (m : ℤ) :
    centeredCube d m = Homogenization.HighContrast.centeredCube d m :=
  rfl

theorem annealedContrast_eq (P : Measure (CoeffSpace d)) (m : ℤ) :
    annealedContrast P m =
      Homogenization.HighContrast.annealedContrast (toRepoLaw P) m := by
  rw [annealedContrast, annealedBlock_eq, blockContrast_ofRepoBlock,
    Homogenization.HighContrast.annealedContrast]
  rfl

/-- The annealed block of a centred cube, in the library vocabulary on both the
law and the cube. -/
theorem annealedBlock_centeredCube_eq (P : Measure (CoeffSpace d)) (m : ℤ) :
    annealedBlock P (centeredCube d m) =
      ofRepoBlock (Homogenization.HighContrast.annealedBlock (toRepoLaw P)
        (Homogenization.HighContrast.centeredCube d m)) :=
  annealedBlock_eq P (centeredCube d m)

/-! ## The law assumptions -/

theorem isStationaryLaw_toRepoLaw {P : Measure (CoeffSpace d)} (h : IsStationaryLaw P) :
    Frozen.IsStationaryLaw (toRepoLaw P) := by
  intro z
  rw [toRepoLaw, show Homogenization.HighContrast.translateCoeff (d := d) z =
    translateCoeff z from rfl, castMeasure_map, castMeasure_eq_iff]
  exact h z

theorem isUnitRangeLaw_toRepoLaw {P : Measure (CoeffSpace d)} (h : IsUnitRangeLaw P) :
    Frozen.IsUnitRangeLaw (toRepoLaw P) := by
  intro U V hU hV hUV
  have h' := h U V hU hV hUV
  have := indep_castMeasure (instMeasurableSpace_eq d) (coeffSigma d U)
    (coeffSigma d V) P h'
  rwa [coeffSigma_eq d U, coeffSigma_eq d V] at this

theorem coarseEllipticityDagger_toRepoLaw {P : Measure (CoeffSpace d)} {g : ℝ}
    {E : BlockMat d} {Ψ : ℝ → ℝ} {K : ℝ} {S : CoeffSpace d → ℝ}
    (h : CoarseEllipticityDagger P g E Ψ K S) :
    Frozen.CoarseEllipticityDagger (toRepoLaw P) g (toRepoBlock E) Ψ K S where
  g_mem := h.g_mem
  refBlock_isSymm := isSymmetricBlockMat_toRepoBlock h.refBlock_isSymm
  refBlock_posDef := blockPosDef_toRepoBlock h.refBlock_posDef
  gauge_admissible := h.gauge_admissible
  one_lt_growthWitness := h.one_lt_growthWitness
  gauge_growth := h.gauge_growth
  source_measurable := measurable_castMeasure (instMeasurableSpace_eq d) h.source_measurable
  source_nonneg := h.source_nonneg
  source_tail := fun t ht => by
    rw [toRepoLaw, castMeasure_real]
    exact h.source_tail t ht
  coarse_bound := by
    rw [toRepoLaw, castMeasure_ae]
    filter_upwards [h.coarse_bound] with a ha m hm k hk w hw
    have := blockMatLoewnerLE_toRepoBlock (ha m hm k hk w hw)
    rwa [toRepoBlock_coarseBlock, toRepoBlock_blockScale] at this

end

end Bridge
end AlgebraicConvergence
end StatementAudit
end HCPoly
