/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi, Amélie Loher
-/
import HCPoly.Provider.Regularity.RoundedUnitCubeDirichletContinuousKDefectResponseDifferenceContraction

/-!
# Geometric continuous K control of the rounded affine iteration

The rounded affine response is iterated from zero.  Consecutive response
differences obey the strict contraction selected before the matrix and
forcing.  The first increment is treated separately by the identity
Dirichlet estimate, so its finiteness is derived from the forcing energy and
is never assumed for an output gradient.
-/

namespace Homogenization
namespace HighContrast

open MeasureTheory
open scoped ENNReal Matrix.Norms.L2Operator

noncomputable section

variable {d : ℕ}

private theorem unitCubeEuclideanL2Field_ext
    (F G : UnitCubeEuclideanL2Field d) (hFG : F.toField = G.toField) : F = G := by
  cases F with
  | mk F hF =>
      cases G with
      | mk G hG =>
          dsimp only at hFG
          subst G
          rfl

/-- The zero-started rounded affine response iteration. -/
noncomputable def roundedUnitCubeDirichletContinuousKIteration
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) : ℕ →
      H10Function (openCubeSet (originCube d 0))
  | 0 => 0
  | n + 1 =>
      roundedUnitCubeDirichletContinuousKIterationStep abar hS h
        (unitCubeGradientEuclideanL2Field
          (roundedUnitCubeDirichletContinuousKIteration abar hS h n))

@[simp] theorem roundedUnitCubeDirichletContinuousKIteration_zero
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) :
    roundedUnitCubeDirichletContinuousKIteration abar hS h 0 = 0 :=
  rfl

@[simp] theorem roundedUnitCubeDirichletContinuousKIteration_succ
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) (n : ℕ) :
    roundedUnitCubeDirichletContinuousKIteration abar hS h (n + 1) =
      roundedUnitCubeDirichletContinuousKIterationStep abar hS h
        (unitCubeGradientEuclideanL2Field
          (roundedUnitCubeDirichletContinuousKIteration abar hS h n)) :=
  rfl

/-- The gradient-field increment between two consecutive affine responses. -/
noncomputable def roundedUnitCubeDirichletContinuousKIterationIncrement
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) (n : ℕ) :
    UnitCubeEuclideanL2Field d :=
  unitCubeGradientEuclideanL2Field
    (roundedUnitCubeDirichletContinuousKIteration abar hS h (n + 1) -
      roundedUnitCubeDirichletContinuousKIteration abar hS h n)

/-- Packaging a difference after taking the gradient agrees with pointwise
subtraction of the two packaged gradients. -/
theorem unitCubeGradientEuclideanL2Field_sub
    (u v : H10Function (openCubeSet (originCube d 0))) :
    unitCubeGradientEuclideanL2Field (u - v) =
      unitCubeEuclideanL2FieldSub
        (unitCubeGradientEuclideanL2Field u)
        (unitCubeGradientEuclideanL2Field v) := by
  apply unitCubeEuclideanL2Field_ext
  funext x
  change (u.toH1Function - v.toH1Function).grad x =
    u.toH1Function.grad x - v.toH1Function.grad x
  exact congrFun (H1Function.sub_grad u.toH1Function v.toH1Function) x

/-- Every successor iterate satisfies the literal affine identity Dirichlet
problem generated by the preceding gradient. -/
theorem roundedUnitCubeDirichletContinuousKIteration_succ_problem
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) (n : ℕ) :
    CubeDirichletDivergenceProblem (originCube d 0)
      (roundedUnitCubeDirichletContinuousKIteration abar hS h (n + 1))
      (unitCubeEuclideanL2FieldAdd h
        (unitCubeEuclideanL2FieldConstMatrixMul
          (roundedReferenceMatrix abar hS - 1)
          (unitCubeGradientEuclideanL2Field
            (roundedUnitCubeDirichletContinuousKIteration abar hS h n)))) := by
  simpa only [roundedUnitCubeDirichletContinuousKIteration_succ] using
    roundedUnitCubeDirichletContinuousKIterationStep_problem abar hS h
      (unitCubeGradientEuclideanL2Field
        (roundedUnitCubeDirichletContinuousKIteration abar hS h n))

/-- The first iterate solves the identity problem with exactly the original
forcing; the defect term vanishes because the iteration starts at zero. -/
theorem roundedUnitCubeDirichletContinuousKIteration_one_problem
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) :
    CubeDirichletDivergenceProblem (originCube d 0)
      (roundedUnitCubeDirichletContinuousKIteration abar hS h 1) h := by
  have hproblem :=
    roundedUnitCubeDirichletContinuousKIteration_succ_problem abar hS h 0
  have hdatum :
      (unitCubeEuclideanL2FieldAdd h
        (unitCubeEuclideanL2FieldConstMatrixMul
          (roundedReferenceMatrix abar hS - 1)
          (unitCubeGradientEuclideanL2Field
            (roundedUnitCubeDirichletContinuousKIteration abar hS h 0)))).toField =
        h.toField := by
    funext x
    change h x + matVecMul (roundedReferenceMatrix abar hS - 1)
      ((0 : H1Function (openCubeSet (originCube d 0))).grad x) = h x
    rw [H1Function.zero_grad]
    simp only [Pi.zero_apply, matVecMul_zero, add_zero]
  rw [hdatum] at hproblem
  simpa only [zero_add] using hproblem

/-- The zeroth packaged increment is exactly the packaged gradient of the
first response. -/
theorem roundedUnitCubeDirichletContinuousKIterationIncrement_zero
    [NeZero d] (abar : Mat d) (hS : (symmPart abar).PosDef)
    (h : UnitCubeEuclideanL2Field d) :
    roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h 0 =
      unitCubeGradientEuclideanL2Field
        (roundedUnitCubeDirichletContinuousKIteration abar hS h 1) := by
  apply unitCubeEuclideanL2Field_ext
  funext x
  change
    ((roundedUnitCubeDirichletContinuousKIteration abar hS h 1).toH1Function -
        (0 : H1Function (openCubeSet (originCube d 0)))).grad x =
      (roundedUnitCubeDirichletContinuousKIteration abar hS h 1).toH1Function.grad x
  rw [H1Function.sub_grad, H1Function.zero_grad]
  simp only [Pi.zero_apply, sub_zero]

/-- For each positive dimension, the fractional order, strict contraction,
and initial-response constant are fixed before all matrix and forcing data.
Finite forcing energy gives a finite first increment, and every later
increment is bounded by the corresponding geometric power. -/
theorem exists_roundedUnitCubeDirichletContinuousKIterationIncrementGeometricBound
    (d : ℕ) [NeZero d] :
    ∃ A : ℝ, 1 ≤ A ∧
      ∃ s : FractionalOrder,
        s.1 < (1 : ℝ) / 12 ∧
          (ENNReal.ofReal A) ^ (2 * s.1) <
            ENNReal.ofReal ((101 : ℝ) / 100) ∧
          (ENNReal.ofReal A) ^ (2 * s.1) *
              ENNReal.ofReal ((1 / 100 : ℝ) ^ 2) <
            ENNReal.ofReal ((101 : ℝ) / 1000000) ∧
          (ENNReal.ofReal A) ^ (2 * s.1) *
              ENNReal.ofReal ((1 / 100 : ℝ) ^ 2) < 1 ∧
          ∃ B : ℝ, 1 ≤ B ∧
            ∀ (abar : Mat d) (hS : (symmPart abar).PosDef)
              (h : UnitCubeEuclideanL2Field d),
              unitCubeNormalizedContinuousKEnergy s h < ∞ →
                unitCubeNormalizedContinuousKEnergy s
                    (roundedUnitCubeDirichletContinuousKIterationIncrement
                      abar hS h 0) ≤
                  (ENNReal.ofReal B) ^ (2 * s.1) *
                    unitCubeNormalizedContinuousKEnergy s h ∧
                unitCubeNormalizedContinuousKEnergy s
                    (roundedUnitCubeDirichletContinuousKIterationIncrement
                      abar hS h 0) < ∞ ∧
                ∀ n : ℕ,
                  unitCubeNormalizedContinuousKEnergy s
                      (roundedUnitCubeDirichletContinuousKIterationIncrement
                        abar hS h n) ≤
                    (((ENNReal.ofReal A) ^ (2 * s.1) *
                        ENNReal.ofReal ((1 / 100 : ℝ) ^ 2)) ^ n) *
                      unitCubeNormalizedContinuousKEnergy s
                        (roundedUnitCubeDirichletContinuousKIterationIncrement
                          abar hS h 0) ∧
                  unitCubeNormalizedContinuousKEnergy s
                      (roundedUnitCubeDirichletContinuousKIterationIncrement
                        abar hS h n) < ∞ := by
  rcases
      exists_roundedUnitCubeDirichletContinuousKIterationStepDifferenceContraction d with
    ⟨A, honeA, s, hs, hfactor, hcoefficient, honeCoefficient, hcontraction⟩
  rcases exists_unitCubeDirichletContinuousKNormalizedEnergyBound d with
    ⟨B, honeB, hidentity⟩
  refine ⟨A, honeA, s, hs, hfactor, hcoefficient, honeCoefficient,
    B, honeB, ?_⟩
  intro abar hS h hhFinite
  let q : ℝ≥0∞ :=
    (ENNReal.ofReal A) ^ (2 * s.1) *
      ENNReal.ofReal ((1 / 100 : ℝ) ^ 2)
  have hfirst :
      unitCubeNormalizedContinuousKEnergy s
          (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h 0) ≤
        (ENNReal.ofReal B) ^ (2 * s.1) *
          unitCubeNormalizedContinuousKEnergy s h := by
    rw [roundedUnitCubeDirichletContinuousKIterationIncrement_zero]
    simpa only [unitCubeNormalizedContinuousKEnergy] using
      hidentity s h
        (roundedUnitCubeDirichletContinuousKIteration abar hS h 1)
        (roundedUnitCubeDirichletContinuousKIteration_one_problem abar hS h)
  have hBFactorFinite : (ENNReal.ofReal B) ^ (2 * s.1) < ∞ := by
    exact ENNReal.rpow_lt_top_of_nonneg
      (mul_nonneg (by norm_num) s.2.1.le) ENNReal.ofReal_ne_top
  have hfirstFinite :
      unitCubeNormalizedContinuousKEnergy s
          (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h 0) < ∞ :=
    hfirst.trans_lt (ENNReal.mul_lt_top hBFactorFinite hhFinite)
  have hrecurrence : ∀ n : ℕ,
      unitCubeNormalizedContinuousKEnergy s
          (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h (n + 1)) ≤
        q * unitCubeNormalizedContinuousKEnergy s
          (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h n) := by
    intro n
    have hstep := hcontraction abar hS h
      (unitCubeGradientEuclideanL2Field
        (roundedUnitCubeDirichletContinuousKIteration abar hS h (n + 1)))
      (unitCubeGradientEuclideanL2Field
        (roundedUnitCubeDirichletContinuousKIteration abar hS h n))
    simpa only [q, roundedUnitCubeDirichletContinuousKIterationIncrement,
      roundedUnitCubeDirichletContinuousKIteration_succ,
      unitCubeGradientEuclideanL2Field_sub] using hstep
  have hgeometric : ∀ n : ℕ,
      unitCubeNormalizedContinuousKEnergy s
          (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h n) ≤
        q ^ n * unitCubeNormalizedContinuousKEnergy s
          (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h 0) := by
    intro n
    induction n with
    | zero => simp
    | succ n ih =>
        calc
          unitCubeNormalizedContinuousKEnergy s
              (roundedUnitCubeDirichletContinuousKIterationIncrement
                abar hS h (n + 1)) ≤
            q * unitCubeNormalizedContinuousKEnergy s
              (roundedUnitCubeDirichletContinuousKIterationIncrement abar hS h n) :=
            hrecurrence n
          _ ≤ q * (q ^ n * unitCubeNormalizedContinuousKEnergy s
              (roundedUnitCubeDirichletContinuousKIterationIncrement
                abar hS h 0)) :=
            mul_le_mul_right ih q
          _ = q ^ (n + 1) * unitCubeNormalizedContinuousKEnergy s
              (roundedUnitCubeDirichletContinuousKIterationIncrement
                abar hS h 0) := by
            rw [pow_succ]
            ring
  refine ⟨hfirst, hfirstFinite, ?_⟩
  intro n
  refine ⟨by simpa only [q] using hgeometric n, ?_⟩
  have hqFinite : q < ∞ := (by
    exact (show q < 1 from by simpa only [q] using honeCoefficient).trans_le le_top)
  exact (hgeometric n).trans_lt
    (ENNReal.mul_lt_top (ENNReal.pow_lt_top hqFinite) hfirstFinite)

end

end HighContrast
end Homogenization
